import type { CaseDefinition } from '../domain/case-definition';

/** Test-only content proving the engine contract. It is not a shipped game case. */
export const verificationCase = {
  schemaVersion: 1,
  id: 'engine-verification',
  contentVersion: 1,
  metadata: {
    title: 'Engine Verification File',
    subtitle: 'Deterministic runtime fixture',
    classification: 'TEST ONLY',
    estimatedMinutes: 1,
    difficulty: 'rookie',
    tags: ['test-fixture'],
  },
  brief: {
    classification: 'TEST ONLY',
    summary: 'Verify that authored facts, player choices, and unlock rules remain deterministic.',
    objectives: [
      { id: 'objective-verify', text: 'Resolve the authored contradiction.' },
    ],
  },
  investigation: {
    startingSceneId: 'scene-desk',
    startingEvidenceIds: [],
    suspects: [],
    locations: [],
    relationships: [],
    timeline: [],
    scenes: [
      {
        id: 'scene-desk',
        kind: 'system',
        title: 'Verification desk',
        summary: 'The controlled starting state.',
        revealsEvidenceIds: ['evidence-header'],
      },
      {
        id: 'scene-archive',
        kind: 'browser',
        title: 'Verification archive',
        summary: 'A scene gated by viewed evidence.',
        openWhen: { kind: 'evidenceViewed', evidenceId: 'evidence-header' },
        revealsEvidenceIds: [
          'evidence-timezone',
          'evidence-decoy',
          'evidence-photo',
          'evidence-document',
          'evidence-message',
          'evidence-cctv',
          'evidence-statement',
        ],
      },
    ],
    evidence: [
      {
        id: 'evidence-header',
        type: 'email',
        title: 'Message header',
        source: 'Fixture inbox',
        summary: 'A controlled email record.',
        from: { name: 'Fixture Sender', address: 'sender@example.test' },
        to: [{ name: 'Fixture Receiver', address: 'receiver@example.test' }],
        sentAtLabel: '09:41 · TEST CLOCK',
        subject: 'Verification header',
        body: [
          { id: 'email-body-1', kind: 'paragraph', text: 'Authored header value.' },
        ],
        attachmentEvidenceIds: [],
      },
      {
        id: 'evidence-timezone',
        type: 'webpage',
        title: 'Timezone record',
        source: 'Fixture archive',
        summary: 'A second controlled record.',
        siteName: 'Fixture Record',
        displayUrl: 'fixture.invalid/timezone',
        headline: 'Timezone record',
        body: [
          { id: 'web-body-1', kind: 'paragraph', text: 'Authored timezone value.' },
        ],
        capturedAtLabel: 'CAPTURED · TEST CLOCK',
      },
      {
        id: 'evidence-decoy',
        type: 'receipt',
        title: 'Irrelevant receipt',
        source: 'Fixture archive',
        summary: 'A deterministic distractor.',
        merchant: 'Fixture Merchant',
        addressLines: ['1 Test Lane'],
        issuedAtLabel: 'TEST CLOCK',
        lines: [
          {
            id: 'receipt-line-1',
            description: 'Unrelated item',
            quantity: 1,
            amountLabel: '10.00',
          },
        ],
        subtotalLabel: '10.00',
        totalLabel: '10.00',
      },
      {
        id: 'evidence-photo',
        type: 'photo',
        title: 'Fixture photograph',
        source: 'Fixture camera',
        summary: 'A photo viewer fixture.',
        image: {
          assetId: 'fixture-photo',
          altText: 'A test-only fixture photograph.',
          width: 1600,
          height: 900,
        },
        caption: 'Test-only image content.',
        annotations: [
          { id: 'photo-mark-1', xPercent: 42, yPercent: 36, label: 'Fixture marker' },
        ],
      },
      {
        id: 'evidence-document',
        type: 'document',
        title: 'Fixture memorandum',
        source: 'Fixture records',
        summary: 'A document viewer fixture.',
        documentType: 'MEMORANDUM',
        author: 'Fixture Author',
        pages: [
          {
            id: 'document-page-1',
            label: 'PAGE 1 OF 1',
            blocks: [
              { id: 'doc-heading-1', kind: 'heading', text: 'Verification memorandum' },
              { id: 'doc-body-1', kind: 'paragraph', text: 'Controlled document body.' },
            ],
          },
        ],
      },
      {
        id: 'evidence-message',
        type: 'message',
        title: 'Fixture conversation',
        source: 'Fixture messenger',
        summary: 'A message viewer fixture.',
        platform: 'Fixture Chat',
        conversationTitle: 'Verification thread',
        participants: [
          { id: 'participant-a', displayName: 'Operator', isDeviceOwner: true },
          { id: 'participant-b', displayName: 'Contact' },
        ],
        messages: [
          {
            id: 'message-1',
            senderId: 'participant-a',
            sentAtLabel: '09:40',
            body: 'Controlled message body.',
            status: 'read',
          },
        ],
      },
      {
        id: 'evidence-cctv',
        type: 'cctv',
        title: 'Fixture CCTV clip',
        source: 'CAM-TEST',
        summary: 'A CCTV viewer fixture.',
        cameraLabel: 'CAM-TEST / ENTRY',
        recordedAtLabel: 'TEST CLOCK',
        durationSeconds: 12,
        video: {
          assetId: 'fixture-cctv-video',
          altText: 'A test-only CCTV clip.',
          width: 1920,
          height: 1080,
        },
        markers: [{ id: 'cctv-mark-1', offsetSeconds: 4, label: 'Movement' }],
      },
      {
        id: 'evidence-statement',
        type: 'statement',
        title: 'Fixture statement',
        source: 'Fixture interview room',
        summary: 'A statement viewer fixture.',
        speakerName: 'Fixture Witness',
        speakerRole: 'Test witness',
        recordedAtLabel: 'TEST CLOCK',
        paragraphs: [
          { id: 'statement-1', kind: 'quote', text: 'Controlled witness statement.' },
        ],
        signedBy: 'Fixture Witness',
      },
    ],
    internet: {
      sites: [
        {
          id: 'site-signal-ledger',
          identity: {
            identityId: 'identity-signal-ledger',
            name: 'Signal Ledger',
            shortName: 'SL',
            fictionalHost: 'signal-ledger.invalid',
            tagline: 'Records before rumors',
            layout: 'newsroom',
            logoText: 'SIGNAL LEDGER',
            typography: 'editorial',
            shape: 'square',
            colors: {
              background: '#f1eee5',
              surface: '#ffffff',
              text: '#181818',
              muted: '#67635c',
              accent: '#9b2f2f',
              accentSecondary: '#1f4d61',
            },
          },
          homePageId: 'ledger-home',
          pages: [
            {
              id: 'ledger-home',
              path: '/',
              title: 'Signal Ledger Front Page',
              description: 'A local verification newsroom.',
              publishedAtLabel: 'TEST EDITION',
              blocks: [
                { id: 'ledger-headline', type: 'heading', level: 1, text: 'Records before rumors' },
                { id: 'ledger-copy', type: 'paragraph', text: 'Controlled local article copy.' },
                {
                  id: 'ledger-quote',
                  type: 'quote',
                  text: 'The archive remembers every revision.',
                  attribution: 'Desk editor',
                },
              ],
              links: [
                {
                  id: 'ledger-to-board',
                  label: 'Community response',
                  targetSiteId: 'site-hushboard',
                  targetPageId: 'board-home',
                  treatment: 'secondary',
                },
              ],
              revealsEvidenceIds: ['evidence-timezone'],
              searchTerms: ['archive', 'timezone', 'verification'],
            },
          ],
        },
        {
          id: 'site-hushboard',
          identity: {
            identityId: 'identity-hushboard',
            name: 'Hushboard',
            shortName: 'HB',
            fictionalHost: 'hushboard.invalid',
            tagline: 'Neighborhood threads, quietly kept',
            layout: 'community',
            logoText: 'hush/board',
            typography: 'friendly',
            shape: 'pill',
            colors: {
              background: '#161c22',
              surface: '#202a33',
              text: '#edf3f6',
              muted: '#9aaab3',
              accent: '#63d1b5',
              accentSecondary: '#f1a45b',
            },
          },
          homePageId: 'board-home',
          pages: [
            {
              id: 'board-home',
              path: '/threads',
              title: 'Local Threads',
              description: 'A fictional neighborhood discussion board.',
              blocks: [
                {
                  id: 'board-post',
                  type: 'post',
                  author: 'NightWindow',
                  handle: '@nightwindow',
                  timestampLabel: 'TEST CLOCK',
                  body: 'Did anyone else notice the archive lights?',
                  reactionLabel: '4 replies',
                },
                {
                  id: 'board-notice',
                  type: 'notice',
                  label: 'MOD NOTE',
                  text: 'This thread is preserved in the local case archive.',
                  tone: 'info',
                },
              ],
              links: [
                {
                  id: 'board-to-ledger',
                  label: 'Read the ledger record',
                  targetSiteId: 'site-signal-ledger',
                  targetPageId: 'ledger-home',
                  treatment: 'inline',
                },
              ],
              revealsEvidenceIds: ['evidence-statement'],
              searchTerms: ['neighborhood', 'archive lights', 'thread'],
            },
          ],
        },
      ],
    },
    deductions: [
      {
        id: 'deduction-origin',
        prompt: 'Which two records establish the contradiction?',
        openWhen: { kind: 'evidenceDiscovered', evidenceId: 'evidence-timezone' },
        minimumEvidence: 2,
        maximumEvidence: 2,
      },
    ],
    accusation: {
      title: 'Verification conclusion',
      prompt: 'Resolve the controlled question.',
      openWhen: { kind: 'deductionSolved', deductionId: 'deduction-origin' },
      questions: [
        {
          id: 'question-actor',
          prompt: 'Which authored option is canonical?',
          options: [
            { id: 'actor-a', label: 'Option A' },
            { id: 'actor-b', label: 'Option B' },
          ],
        },
      ],
    },
  },
  canonicalTruth: {
    deductionSolutions: {
      'deduction-origin': {
        requiredEvidenceIds: ['evidence-header', 'evidence-timezone'],
      },
    },
    accusationAnswers: {
      'question-actor': 'actor-b',
    },
    requiredDeductionIds: ['deduction-origin'],
    resolution: {
      headline: 'Verification complete',
      summary: 'The deterministic authored path was resolved.',
    },
  },
  scoring: {
    maximumScore: 100,
    incorrectDeductionPenalty: 7,
    incorrectAccusationPenalty: 13,
  },
} as const satisfies CaseDefinition;
