import type {
  LocationDefinition,
  RelationshipDefinition,
  SuspectDefinition,
  TimelineEventDefinition,
} from '../../../case-engine';

export const CASE001_SUSPECTS = [
  {
    id: 'suspect-celeste-vane',
    name: 'Dr. Celeste Vane',
    role: 'Hartwell Museum director and loan custodian',
    summary:
      'A meticulous director whose reputation and museum expansion plan depend on the Asterion exhibition succeeding.',
    statedAlibi:
      'Says she remained in the Grand Rotunda with donors from 21:14 until the alarm at 21:25.',
    tags: ['custodian', 'museum-board', 'insurance-authority'],
  },
  {
    id: 'suspect-adrian-cross',
    name: 'Adrian Cross',
    role: 'Head of museum security',
    summary:
      'Designed the gala security plan and controls the camera, credential, and service-access systems.',
    statedAlibi:
      'Says he monitored the entire transfer window from the east security desk.',
    tags: ['security', 'systems-access', 'master-keyholder'],
  },
  {
    id: 'suspect-mara-bell',
    name: 'Mara Bell',
    role: 'Senior gemstone conservator',
    summary:
      'Performed the final condition inspection and openly criticized the display plinth’s climate stability.',
    statedAlibi:
      'Says she was in the Restoration Lab on a call from 21:11 until 21:24.',
    tags: ['conservator', 'display-access', 'technical-expertise'],
  },
  {
    id: 'suspect-julian-rook',
    name: 'Julian Rook',
    role: 'Beneficiary of the Rook family diamond trust',
    summary:
      'The glamorous but cash-strained heir cannot sell the stone while it remains bound to the family trust.',
    statedAlibi:
      'Says he took a private creditor call on the Roof Terrace from 21:13 until 21:24.',
    tags: ['beneficiary', 'financial-pressure', 'gala-host'],
  },
  {
    id: 'suspect-nia-okafor',
    name: 'Nia Okafor',
    role: 'Investigative culture reporter',
    summary:
      'Entered on a press credential while researching museum labor disputes and weaknesses in private collections.',
    statedAlibi:
      'Says she recorded an uninterrupted field segment in the Press Alcove during the theft window.',
    tags: ['press', 'unauthorized-stream', 'confidential-sources'],
  },
  {
    id: 'suspect-elias-ward',
    name: 'Elias Ward',
    role: 'Private auction appraiser',
    summary:
      'Authenticated the Asterion for the loan and maintains discreet relationships with international collectors.',
    statedAlibi:
      'Says he remained at the Auction Lounge tasting table between 21:10 and 21:24.',
    tags: ['appraiser', 'buyer-network', 'prior-access'],
  },
] as const satisfies readonly SuspectDefinition[];

export const CASE001_LOCATIONS = [
  {
    id: 'location-asterion-gallery',
    name: 'Asterion Gallery',
    kind: 'gallery',
    summary: 'Gallery Four, centered on a sealed climate plinth beneath a camera dome.',
  },
  {
    id: 'location-grand-rotunda',
    name: 'Grand Rotunda',
    kind: 'hospitality',
    summary: 'The gala’s donor floor, stage, press riser, and primary guest circulation space.',
  },
  {
    id: 'location-security-annex',
    name: 'East Security Annex',
    kind: 'security',
    summary: 'Camera control, credential administration, key issue, and incident logging.',
  },
  {
    id: 'location-restoration-lab',
    name: 'Restoration Laboratory',
    kind: 'workspace',
    summary: 'A biometric-controlled conservation room with instrument and call records.',
  },
  {
    id: 'location-east-corridor',
    name: 'East Service Corridor',
    kind: 'service',
    summary: 'A staff-only passage connecting the annex to the rear cavity of Gallery Four.',
  },
  {
    id: 'location-auction-lounge',
    name: 'Auction Lounge',
    kind: 'hospitality',
    summary: 'A private hospitality room operated for appraisers, lenders, and major donors.',
  },
  {
    id: 'location-roof-terrace',
    name: 'Roof Terrace',
    kind: 'exterior',
    summary: 'An exposed terrace with one camera, poor reception, and a single interior door.',
  },
  {
    id: 'location-press-alcove',
    name: 'Press Alcove',
    kind: 'media',
    summary: 'A sound-damped recording booth overlooking the Rotunda stage.',
  },
  {
    id: 'location-forensics-bench',
    name: 'Device Forensics Bench',
    kind: 'workspace',
    summary:
      'The incident-room bench where seized handsets, lockers, and personal effects are imaged under warrant.',
  },
  {
    id: 'location-loading-lockers',
    name: 'Loading Dock Locker Bay',
    kind: 'storage',
    summary: 'Equipment lockers, retired emergency radios, and the after-hours delivery cage.',
  },
] as const satisfies readonly LocationDefinition[];

export const CASE001_RELATIONSHIPS = [
  {
    id: 'relationship-celeste-julian',
    fromSuspectId: 'suspect-celeste-vane',
    toSuspectId: 'suspect-julian-rook',
    label: 'Custodian and beneficiary',
    summary:
      'Vane administers the museum loan; Rook has repeatedly asked her to release the diamond from trust restrictions.',
    openWhen: { kind: 'evidenceDiscovered', evidenceId: 'evidence-message-celeste-board' },
  },
  {
    id: 'relationship-celeste-mara',
    fromSuspectId: 'suspect-celeste-vane',
    toSuspectId: 'suspect-mara-bell',
    label: 'Director and former protégé',
    summary:
      'Vane recruited Bell, but their correspondence shows escalating disagreement over display safety.',
    openWhen: { kind: 'evidenceDiscovered', evidenceId: 'evidence-email-restoration-report' },
  },
  {
    id: 'relationship-mara-nia',
    fromSuspectId: 'suspect-mara-bell',
    toSuspectId: 'suspect-nia-okafor',
    label: 'Confidential source contact',
    summary:
      'Bell privately supplied Okafor with climate-control concerns before the gala.',
    openWhen: { kind: 'evidenceDiscovered', evidenceId: 'evidence-message-mara-nia' },
  },
  {
    id: 'relationship-adrian-elias',
    fromSuspectId: 'suspect-adrian-cross',
    toSuspectId: 'suspect-elias-ward',
    label: 'Undisclosed financial contact',
    summary:
      'A private message channel and transfer record contradict both men’s claim that they barely know one another.',
    openWhen: { kind: 'evidenceDiscovered', evidenceId: 'evidence-message-adrian-elias' },
  },
  {
    id: 'relationship-julian-elias',
    fromSuspectId: 'suspect-julian-rook',
    toSuspectId: 'suspect-elias-ward',
    label: 'Former auction client',
    summary:
      'Ward previously appraised two Rook family pieces but declined a private sale of the trust-bound Asterion.',
    openWhen: { kind: 'evidenceDiscovered', evidenceId: 'evidence-web-vane-finances' },
  },
  {
    id: 'relationship-adrian-nia',
    fromSuspectId: 'suspect-adrian-cross',
    toSuspectId: 'suspect-nia-okafor',
    label: 'Prior professional conflict',
    summary:
      'Okafor’s earlier security exposé named Cross, who later attempted to revoke her gala credential.',
    openWhen: { kind: 'evidenceDiscovered', evidenceId: 'evidence-web-nia-livestream' },
  },
] as const satisfies readonly RelationshipDefinition[];

export const CASE001_TIMELINE = [
  {
    id: 'timeline-1905-condition-check',
    timeLabel: '19:05',
    sortOrder: 1905,
    title: 'Final condition check signed',
    summary: 'Bell and Vane record the authentic stone, seal number, and distinctive feather inclusion.',
    locationId: 'location-asterion-gallery',
    suspectIds: ['suspect-celeste-vane', 'suspect-mara-bell'],
    sourceEvidenceIds: ['evidence-doc-chain-custody'],
  },
  {
    id: 'timeline-1912-plinth-locked',
    timeLabel: '19:12',
    sortOrder: 1912,
    title: 'Display enters gala mode',
    summary: 'The public glass seal is locked; the concealed service hatch remains under electronic access control.',
    locationId: 'location-asterion-gallery',
    suspectIds: ['suspect-mara-bell'],
    sourceEvidenceIds: ['evidence-doc-plinth-sop'],
  },
  {
    id: 'timeline-1930-doors',
    timeLabel: '19:30',
    sortOrder: 1930,
    title: 'Gala doors open',
    summary: 'Public programming begins under the published Midnight Gallery schedule.',
    locationId: 'location-grand-rotunda',
    suspectIds: [],
    sourceEvidenceIds: ['evidence-web-gala-schedule'],
  },
  {
    id: 'timeline-2006-security-shift',
    timeLabel: '20:06',
    sortOrder: 2006,
    title: 'Cross assumes east command',
    summary: 'The shift roster places Cross at the East Security Annex with credential-administration authority.',
    locationId: 'location-security-annex',
    suspectIds: ['suspect-adrian-cross'],
    sourceEvidenceIds: ['evidence-email-security-roster'],
  },
  {
    id: 'timeline-2041-julian-lounge',
    timeLabel: '20:41',
    sortOrder: 2041,
    title: 'Rook enters the auction reception',
    summary: 'A hospitality receipt records his table before he later moves to the terrace.',
    locationId: 'location-auction-lounge',
    suspectIds: ['suspect-julian-rook'],
    sourceEvidenceIds: ['evidence-receipt-julian-restaurant'],
  },
  {
    id: 'timeline-2052-credential-clone',
    timeLabel: '20:52',
    sortOrder: 2052,
    title: 'Duplicate credential generated',
    summary:
      'Admin terminal AS-01 creates a second token from the revoked MC-04 profile. Only the administrator session holder is recorded as present.',
    locationId: 'location-security-annex',
    suspectIds: ['suspect-adrian-cross'],
    sourceEvidenceIds: ['evidence-doc-admin-audit', 'evidence-email-badge-alert'],
    openWhen: { kind: 'evidenceDiscovered', evidenceId: 'evidence-doc-admin-audit' },
  },
  {
    id: 'timeline-2102-broadcast',
    timeLabel: '21:02',
    sortOrder: 2102,
    title: 'Live gala coverage begins',
    summary: 'Channel Eight’s wide feed records the Rotunda and donor floor continuously.',
    locationId: 'location-grand-rotunda',
    suspectIds: ['suspect-celeste-vane'],
    sourceEvidenceIds: ['evidence-web-channel8-gallery'],
  },
  {
    id: 'timeline-2108-mara-lab',
    timeLabel: '21:08',
    sortOrder: 2108,
    title: 'Bell enters Restoration Lab',
    summary: 'Biometric entry and instrument autosave begin a continuous laboratory session.',
    locationId: 'location-restoration-lab',
    suspectIds: ['suspect-mara-bell'],
    sourceEvidenceIds: ['evidence-doc-restoration-log'],
  },
  {
    id: 'timeline-2110-elias-wine',
    timeLabel: '21:10',
    sortOrder: 2110,
    title: 'Ward’s tasting ticket opens',
    summary: 'A personalized lounge ticket is scanned at the appraiser table.',
    locationId: 'location-auction-lounge',
    suspectIds: ['suspect-elias-ward'],
    sourceEvidenceIds: ['evidence-receipt-auction-wine'],
  },
  {
    id: 'timeline-2111-source-call',
    timeLabel: '21:11',
    sortOrder: 2111,
    title: 'Bell and Okafor call begins',
    summary: 'The encrypted thread records a live call while Bell’s lab instrument continues autosaving.',
    locationId: 'location-restoration-lab',
    suspectIds: ['suspect-mara-bell', 'suspect-nia-okafor'],
    sourceEvidenceIds: ['evidence-message-mara-nia', 'evidence-doc-restoration-log'],
  },
  {
    id: 'timeline-2112-cross-leaves',
    timeLabel: '21:12',
    sortOrder: 2112,
    title: 'Uniformed figure leaves annex side',
    summary: 'The east corridor source records movement away from the security annex.',
    locationId: 'location-east-corridor',
    suspectIds: ['suspect-adrian-cross'],
    sourceEvidenceIds: ['evidence-cctv-east-corridor'],
    openWhen: { kind: 'deductionSolved', deductionId: 'deduction-camera-replay' },
  },
  {
    id: 'timeline-2113-julian-terrace',
    timeLabel: '21:13',
    sortOrder: 2113,
    title: 'Rook reaches terrace',
    summary: 'Roof camera records Rook entering and beginning a phone call.',
    locationId: 'location-roof-terrace',
    suspectIds: ['suspect-julian-rook'],
    sourceEvidenceIds: ['evidence-cctv-roof-terrace'],
  },
  {
    id: 'timeline-2114-celeste-photo',
    timeLabel: '21:14',
    sortOrder: 2114,
    title: 'Vane appears in donor photograph',
    summary: 'A broadcast still places Vane in the Rotunda as the program introduces the quartet.',
    locationId: 'location-grand-rotunda',
    suspectIds: ['suspect-celeste-vane'],
    sourceEvidenceIds: ['evidence-photo-gala-wide'],
  },
  {
    id: 'timeline-2114-ward-niche',
    timeLabel: '21:14:06',
    sortOrder: 2114.06,
    title: 'Ward enters the lounge telephone niche',
    summary:
      'The niche extension carries one uninterrupted corded call until 21:22:58, and the lounge camera records no exit from the recess.',
    locationId: 'location-auction-lounge',
    suspectIds: ['suspect-elias-ward'],
    sourceEvidenceIds: [
      'evidence-cctv-auction-lounge',
      'evidence-doc-lounge-call-record',
    ],
    openWhen: {
      kind: 'evidenceDiscovered',
      evidenceId: 'evidence-doc-lounge-call-record',
    },
  },
  {
    id: 'timeline-2116-nia-records',
    timeLabel: '21:16',
    sortOrder: 2116,
    title: 'Okafor starts field recording',
    summary: 'The local archive preserves a continuous take with Rotunda audio through 21:22.',
    locationId: 'location-press-alcove',
    suspectIds: ['suspect-nia-okafor'],
    sourceEvidenceIds: ['evidence-web-nia-livestream'],
  },
  {
    id: 'timeline-2117-transfer',
    timeLabel: '21:17',
    sortOrder: 2117,
    title: 'Generator transfer begins',
    summary: 'The scheduled test dims gallery lighting and raises a control-room warning for ninety seconds.',
    locationId: 'location-security-annex',
    suspectIds: ['suspect-adrian-cross'],
    sourceEvidenceIds: ['evidence-email-power-test'],
  },
  {
    id: 'timeline-2117-panel',
    timeLabel: '21:17:43',
    sortOrder: 2117.43,
    title: 'East service panel opens',
    summary:
      'The access log records duplicate token DT-884, not Bell’s physical MC-04-P card, which stays sealed in the office safe while she is inside the lab.',
    locationId: 'location-east-corridor',
    suspectIds: [],
    sourceEvidenceIds: ['evidence-email-badge-alert', 'evidence-doc-admin-audit'],
    openWhen: { kind: 'deductionSolved', deductionId: 'deduction-cloned-credential' },
  },
  {
    id: 'timeline-2118-corridor',
    timeLabel: '21:18',
    sortOrder: 2118,
    title: 'Figure crosses east corridor',
    summary: 'Infrared frames show a security-cut jacket moving toward the gallery service cavity.',
    locationId: 'location-east-corridor',
    suspectIds: ['suspect-adrian-cross'],
    sourceEvidenceIds: ['evidence-cctv-east-corridor'],
    openWhen: { kind: 'deductionSolved', deductionId: 'deduction-camera-replay' },
  },
  {
    id: 'timeline-2119-hatch',
    timeLabel: '21:19',
    sortOrder: 2119,
    title: 'Service hatch tool marks made',
    summary: 'Fresh triangular impressions are later found beneath the intact public seal.',
    locationId: 'location-asterion-gallery',
    suspectIds: [],
    sourceEvidenceIds: ['evidence-photo-toolmarks'],
    openWhen: { kind: 'evidenceDiscovered', evidenceId: 'evidence-photo-toolmarks' },
  },
  {
    id: 'timeline-2121-feed-resumes',
    timeLabel: '21:21',
    sortOrder: 2121,
    title: 'Gallery feed resumes live frames',
    summary: 'Frame hashes stop repeating; the display appears unchanged at normal viewing distance.',
    locationId: 'location-asterion-gallery',
    suspectIds: [],
    sourceEvidenceIds: ['evidence-cctv-gallery', 'evidence-doc-camera-hash'],
  },
  {
    id: 'timeline-2123-elias-lounge',
    timeLabel: '21:23',
    sortOrder: 2123,
    title: 'Ward returns to camera center',
    summary: 'The lounge camera clearly records Ward after an interval at the room’s unmonitored telephone niche.',
    locationId: 'location-auction-lounge',
    suspectIds: ['suspect-elias-ward'],
    sourceEvidenceIds: ['evidence-cctv-auction-lounge'],
  },
  {
    id: 'timeline-2124-calls-end',
    timeLabel: '21:24',
    sortOrder: 2124,
    title: 'Parallel calls end',
    summary: 'Bell’s source call and Rook’s creditor call both terminate within the minute.',
    suspectIds: ['suspect-mara-bell', 'suspect-julian-rook', 'suspect-nia-okafor'],
    sourceEvidenceIds: ['evidence-message-mara-nia', 'evidence-message-julian-creditor'],
  },
  {
    id: 'timeline-2125-discovery',
    timeLabel: '21:25',
    sortOrder: 2125,
    title: 'Facet discrepancy reported',
    summary: 'Vane notices the display stone lacks the Asterion’s feather inclusion and orders a lockdown.',
    locationId: 'location-asterion-gallery',
    suspectIds: ['suspect-celeste-vane'],
    sourceEvidenceIds: ['evidence-statement-celeste', 'evidence-photo-replica-macro'],
  },
  {
    id: 'timeline-2131-lockdown',
    timeLabel: '21:31',
    sortOrder: 2131,
    title: 'Museum lockdown completes',
    summary: 'The loading cage closes before any after-hours equipment handoff can occur.',
    locationId: 'location-loading-lockers',
    suspectIds: ['suspect-adrian-cross'],
    sourceEvidenceIds: ['evidence-message-gala-staff'],
  },
  {
    id: 'timeline-2340-recovery',
    timeLabel: '23:40',
    sortOrder: 2340,
    title: 'Radio R-17 examined',
    summary: 'The retired radio’s battery cavity contains a sealed gemstone packet matching the chain record.',
    locationId: 'location-loading-lockers',
    suspectIds: [],
    sourceEvidenceIds: ['evidence-photo-recovered-asterion'],
    openWhen: { kind: 'deductionSolved', deductionId: 'deduction-diamond-cache' },
  },
] as const satisfies readonly TimelineEventDefinition[];
