import type { EvidenceDefinition } from '../../../case-engine';

export const CASE001_EVIDENCE = [
  // PHOTOGRAPHS
  {
    id: 'evidence-photo-empty-plinth',
    type: 'photo',
    title: 'Gallery Four plinth at lockdown',
    source: 'Scene Unit / HART-04',
    summary: 'The display remains sealed, but the stone inside lacks the documented feather inclusion.',
    capturedAtLabel: '21:34 · 14 OCT',
    tags: ['physical', 'crime-scene', 'display'],
    image: {
      assetId: 'case001-photo-empty-plinth',
      altText: 'A sealed museum plinth holding a pale diamond beneath gallery lighting.',
      width: 1600,
      height: 1067,
    },
    caption: 'Public glass seal H4-771 remains unbroken after the substitution window.',
    annotations: [
      { id: 'plinth-mark-seal', xPercent: 72, yPercent: 23, label: 'Seal H4-771 intact' },
      { id: 'plinth-mark-hatch', xPercent: 18, yPercent: 78, label: 'Rear service cavity' },
    ],
  },
  {
    id: 'evidence-photo-replica-macro',
    type: 'photo',
    title: 'Substitute stone macro study',
    source: 'Restoration microscope / RM-2',
    summary: 'A resin-filled replica carries a laser-cut star but lacks the Asterion’s natural internal feather.',
    capturedAtLabel: '21:49 · 14 OCT',
    tags: ['physical', 'replica', 'gemology'],
    image: {
      assetId: 'case001-photo-replica-macro',
      altText: 'A magnified faceted stone with a tiny manufactured star mark near its girdle.',
      width: 1600,
      height: 1067,
    },
    caption: 'The five-point micro-mark corresponds to Prism Props fabrication stock.',
    annotations: [
      { id: 'replica-mark-star', xPercent: 61, yPercent: 58, label: 'Laser-cut five-point star' },
      { id: 'replica-mark-resin', xPercent: 38, yPercent: 42, label: 'Resin-filled inclusion' },
    ],
  },
  {
    id: 'evidence-photo-toolmarks',
    type: 'photo',
    title: 'Service hatch tool impressions',
    source: 'Forensic macro unit / Gallery Four',
    summary: 'Fresh triangular impressions appear beneath the intact public seal on the concealed service hatch.',
    capturedAtLabel: '22:17 · 14 OCT',
    tags: ['physical', 'toolmark', 'service-route'],
    image: {
      assetId: 'case001-photo-toolmarks',
      altText: 'Close-up of fresh triangular scratches on a brass service-hatch fastener.',
      width: 1600,
      height: 1067,
    },
    caption: 'Impression width: 8.4 mm, matching the museum security bypass-key profile.',
    annotations: [
      { id: 'toolmark-triangle', xPercent: 52, yPercent: 47, label: '8.4 mm triangular seat' },
      { id: 'toolmark-brass', xPercent: 69, yPercent: 64, label: 'Fresh brass displacement' },
    ],
  },
  {
    id: 'evidence-photo-navy-fiber',
    type: 'photo',
    title: 'Navy aramid fiber under panel screw',
    source: 'East Corridor trace collection',
    summary: 'A torn uniform-grade fiber is trapped under the service panel’s lower retaining screw.',
    capturedAtLabel: '22:24 · 14 OCT',
    tags: ['physical', 'fiber', 'uniform'],
    image: {
      assetId: 'case001-photo-navy-fiber',
      altText: 'A short navy fiber caught beneath a metal panel screw beside an evidence scale.',
      width: 1600,
      height: 1067,
    },
    caption: 'Twisted aramid blend with museum-security supplier dye lot N-44.',
    annotations: [
      { id: 'fiber-mark-strand', xPercent: 45, yPercent: 51, label: 'Navy aramid strand' },
      { id: 'fiber-mark-screw', xPercent: 67, yPercent: 44, label: 'Panel screw 4B' },
    ],
  },
  {
    id: 'evidence-photo-gala-wide',
    type: 'photo',
    title: 'Rotunda donor photograph',
    source: 'Channel Eight press pool',
    summary: 'A wide still places Celeste Vane among donors at 21:14 and again in the same sequence at 21:20.',
    capturedAtLabel: '21:14:36 · 14 OCT',
    tags: ['digital', 'alibi', 'rotunda'],
    image: {
      assetId: 'case001-photo-gala-wide',
      altText: 'A crowded museum rotunda during a formal evening gala.',
      width: 1600,
      height: 900,
    },
    caption: 'Broadcast timecode is independently signed by the Channel Eight field encoder.',
    annotations: [
      { id: 'gala-mark-celeste', xPercent: 63, yPercent: 48, label: 'Dr. Vane' },
      { id: 'gala-mark-stage', xPercent: 30, yPercent: 37, label: 'Quartet introduction' },
    ],
  },
  {
    id: 'evidence-photo-keyring',
    type: 'photo',
    title: 'Security key issue photograph',
    source: 'East Annex locker camera',
    summary: 'A pre-shift image records Cross’s keyring with a triangular bypass key and Locker B tag.',
    capturedAtLabel: '20:07:11 · 14 OCT',
    tags: ['physical', 'key', 'locker'],
    image: {
      assetId: 'case001-photo-keyring',
      altText: 'A navy security jacket beside a keyring with a triangular brass key and B locker tag.',
      width: 1600,
      height: 1067,
    },
    caption: 'The jacket’s right cuff seam is visibly frayed before the theft window.',
    annotations: [
      { id: 'keyring-mark-key', xPercent: 47, yPercent: 62, label: 'Triangular bypass key' },
      { id: 'keyring-mark-tag', xPercent: 62, yPercent: 51, label: 'Locker B tag' },
      { id: 'keyring-mark-cuff', xPercent: 28, yPercent: 69, label: 'Frayed navy cuff' },
    ],
  },
  {
    id: 'evidence-photo-recovered-asterion',
    type: 'photo',
    title: 'Asterion recovery photograph',
    source: 'Loading Locker B / Recovery Unit',
    summary: 'A gemstone packet recovered from radio R-17 matches the chain record, weight, and natural inclusion map.',
    capturedAtLabel: '23:40 · 14 OCT',
    tags: ['physical', 'recovery', 'diamond'],
    image: {
      assetId: 'case001-photo-recovered-asterion',
      altText: 'A large diamond in a sealed evidence packet beside an opened emergency-radio battery.',
      width: 1600,
      height: 1067,
    },
    caption: 'Recovered before the loading dock reopened; packet exterior carries navy fibers.',
    annotations: [
      { id: 'recovery-mark-feather', xPercent: 42, yPercent: 43, label: 'Natural feather inclusion' },
      { id: 'recovery-mark-radio', xPercent: 76, yPercent: 62, label: 'Radio R-17 battery shell' },
    ],
  },

  // DOCUMENTS
  {
    id: 'evidence-doc-chain-custody',
    type: 'document',
    title: 'Asterion chain-of-custody record',
    source: 'Hartwell Registrar Office',
    summary: 'The signed intake record documents the authentic stone, seal, weight, and natural inclusion map.',
    capturedAtLabel: 'FILED 19:12 · 14 OCT',
    tags: ['physical', 'custody', 'baseline'],
    documentType: 'CHAIN OF CUSTODY / HC-771',
    author: 'Registrar Len Cho',
    pages: [
      {
        id: 'custody-page-1',
        label: 'PAGE 1 OF 2',
        blocks: [
          { id: 'custody-heading-1', kind: 'heading', text: 'THE ASTERION — GALA TRANSFER' },
          { id: 'custody-body-1', kind: 'paragraph', text: 'Item: 42.18 carat colorless diamond. Museum seal H4-771. Recorded weight confirmed at 19:05.' },
          { id: 'custody-body-2', kind: 'paragraph', text: 'Primary identifier: feather-shaped inclusion below the lower-left crown facet. Secondary identifier: asymmetrical natural at girdle position 7.' },
          { id: 'custody-quote-1', kind: 'quote', text: 'Condition unchanged. Approved for sealed display.' },
        ],
      },
      {
        id: 'custody-page-2',
        label: 'PAGE 2 OF 2',
        blocks: [
          { id: 'custody-heading-2', kind: 'heading', text: 'SIGNATURES' },
          { id: 'custody-body-3', kind: 'paragraph', text: 'Custodian: Dr. Celeste Vane · 19:07. Conservator: Mara Bell · 19:06. Appraiser witness: Elias Ward · 18:42.' },
          { id: 'custody-body-4', kind: 'paragraph', text: 'Public glass seal applied 19:12. Rear maintenance hatch governed by staff credential plus mechanical bypass.' },
        ],
      },
    ],
  },
  {
    id: 'evidence-doc-plinth-sop',
    type: 'document',
    title: 'Gallery Four plinth service procedure',
    source: 'Hartwell Facilities Manual',
    summary: 'The plinth can be opened from the rear cavity without disturbing the visible glass seal.',
    tags: ['physical', 'procedure', 'access'],
    documentType: 'RESTRICTED SERVICE PROCEDURE / P4-C',
    author: 'Hartwell Facilities Engineering',
    pages: [
      {
        id: 'plinth-sop-page-1',
        label: 'PAGE 1 OF 2',
        blocks: [
          { id: 'plinth-sop-heading-1', kind: 'heading', text: 'DUAL-ACCESS DISPLAY PLINTH' },
          { id: 'plinth-sop-body-1', kind: 'paragraph', text: 'Public seal protects the glass hood. Maintenance access is through Gallery Four east service cavity and does not break the hood seal.' },
          { id: 'plinth-sop-redaction-1', kind: 'redaction', characterCount: 28 },
        ],
      },
      {
        id: 'plinth-sop-page-2',
        label: 'PAGE 2 OF 2',
        blocks: [
          { id: 'plinth-sop-heading-2', kind: 'heading', text: 'AUTHORIZED OVERRIDE' },
          { id: 'plinth-sop-body-2', kind: 'paragraph', text: 'Electronic credential can be bypassed by 8.4 mm triangular security key during alarm or battery-service conditions.' },
          { id: 'plinth-sop-body-3', kind: 'paragraph', text: 'Issued bypass key: Security Command set K-2.' },
        ],
      },
    ],
  },
  {
    id: 'evidence-doc-camera-hash',
    type: 'document',
    title: 'Gallery camera frame-hash analysis',
    source: 'Digital Forensics Unit',
    summary: 'Ninety seconds of Gallery Four footage repeats an earlier segment while the recorder reports a live feed.',
    capturedAtLabel: '22:03 · 14 OCT',
    tags: ['digital', 'camera', 'replay'],
    documentType: 'FRAME INTEGRITY REPORT / DF-118',
    author: 'Analyst I. Sato',
    pages: [
      {
        id: 'hash-page-1',
        label: 'PAGE 1 OF 2',
        blocks: [
          { id: 'hash-heading-1', kind: 'heading', text: 'REPEATED FRAME SEQUENCE' },
          { id: 'hash-body-1', kind: 'paragraph', text: 'Frames stamped 21:17:31 through 21:19:01 are byte-identical to frames 21:09:44 through 21:11:14 after metadata removal.' },
          { id: 'hash-body-2', kind: 'paragraph', text: 'Lighting noise and visitor reflections repeat exactly. Natural live footage cannot reproduce this hash series.' },
        ],
      },
      {
        id: 'hash-page-2',
        label: 'PAGE 2 OF 2',
        blocks: [
          { id: 'hash-heading-2', kind: 'heading', text: 'INJECTION ORIGIN' },
          { id: 'hash-body-3', kind: 'paragraph', text: 'Replay command entered through security VLAN port EAST-AS01. Local recorder checksum was recomputed at 21:21:04.' },
          { id: 'hash-quote-1', kind: 'quote', text: 'The gallery feed is not a reliable alibi during the transfer interval.' },
        ],
      },
    ],
  },
  {
    id: 'evidence-doc-admin-audit',
    type: 'document',
    title: 'Credential administration audit',
    source: 'Hartwell Access Control / AS-01',
    summary: 'A second token was generated from Mara Bell’s revoked credential profile during Cross’s administrator session.',
    capturedAtLabel: 'EXPORTED 22:11 · 14 OCT',
    tags: ['digital', 'credential', 'audit'],
    documentType: 'IMMUTABLE ACCESS AUDIT',
    author: 'Hartwell Access Control',
    pages: [
      {
        id: 'admin-page-1',
        label: 'PAGE 1 OF 1',
        blocks: [
          { id: 'admin-heading-1', kind: 'heading', text: 'ADMIN SESSION AS-01 / A.CROSS' },
          { id: 'admin-body-1', kind: 'paragraph', text: '20:49:08 — Administrator session opened with hardware key AC-K2.' },
          { id: 'admin-body-2', kind: 'paragraph', text: '20:52:14 — Legacy profile MC-04 selected. Replacement token DT-884 encoded.' },
          { id: 'admin-body-3', kind: 'paragraph', text: '20:52:26 — Duplicate-credential warning routed to security.alerts and marked acknowledged.' },
          { id: 'admin-body-4', kind: 'paragraph', text: '21:17:43 — Token DT-884 accepted at EAST-PANEL-4.' },
        ],
      },
    ],
  },
  {
    id: 'evidence-doc-restoration-log',
    type: 'document',
    title: 'Restoration Lab instrument log',
    source: 'Spectrometer RM-2 / biometric door',
    summary: 'Biometric and autosave events place Mara Bell inside the lab throughout the critical window.',
    capturedAtLabel: 'EXPORTED 22:15 · 14 OCT',
    tags: ['digital', 'alibi', 'laboratory'],
    documentType: 'INSTRUMENT SESSION LOG',
    author: 'RM-2 Automated Record',
    pages: [
      {
        id: 'restoration-log-page-1',
        label: 'PAGE 1 OF 1',
        blocks: [
          { id: 'restoration-log-heading', kind: 'heading', text: 'SESSION MB-771' },
          { id: 'restoration-log-body-1', kind: 'paragraph', text: '21:08:09 — Mara Bell biometric entry. 21:09:44 — RM-2 operator confirmation.' },
          { id: 'restoration-log-body-2', kind: 'paragraph', text: 'Autosaves containing live focus and stage coordinates: 21:12, 21:15, 21:18, 21:21, 21:23.' },
          { id: 'restoration-log-body-3', kind: 'paragraph', text: '21:24:18 — Session closed. 21:24:31 — Mara Bell biometric exit.' },
        ],
      },
    ],
  },
  {
    id: 'evidence-doc-radio-inventory',
    type: 'document',
    title: 'Retired emergency-radio inventory',
    source: 'Loading Dock Equipment Office',
    summary: 'Radio R-17 was moved into Loading Locker B under a security work order on gala morning.',
    capturedAtLabel: 'PRINTED 09:18 · 14 OCT',
    tags: ['physical', 'inventory', 'locker'],
    documentType: 'EQUIPMENT RETIREMENT SHEET',
    author: 'Facilities Clerk J. Pike',
    pages: [
      {
        id: 'radio-page-1',
        label: 'PAGE 1 OF 1',
        blocks: [
          { id: 'radio-heading-1', kind: 'heading', text: 'RADIO BATCH R-12 — R-19' },
          { id: 'radio-body-1', kind: 'paragraph', text: 'R-17: battery failure; battery shell retained for parts. Temporary location: Loading Locker B.' },
          { id: 'radio-body-2', kind: 'paragraph', text: 'Transfer requested by Security Command work order SC-204. Locker seal to be replaced after gala.' },
          { id: 'radio-body-3', kind: 'paragraph', text: 'Battery cavity depth allows storage of components up to 74 × 42 × 18 mm.' },
        ],
      },
    ],
  },

  {
    id: 'evidence-doc-cross-debt',
    type: 'document',
    title: 'Private lending demand notice',
    source: 'Seized from Cross locker / East Annex',
    summary:
      'A private lender demands ninety-six thousand from Adrian Cross and refers to the balance as a called marker.',
    capturedAtLabel: 'SEIZED 22:31 · 14 OCT',
    tags: ['physical', 'financial', 'motive'],
    documentType: 'FINAL DEMAND / PRIVATE NOTE',
    author: 'Vance Holloway Private Lending',
    pages: [
      {
        id: 'debt-page-1',
        label: 'PAGE 1 OF 2',
        blocks: [
          { id: 'debt-heading-1', kind: 'heading', text: 'FINAL DEMAND — ACCOUNT AC-7731' },
          { id: 'debt-body-1', kind: 'paragraph', text: 'Borrower: A. Cross. Outstanding principal and accrued interest: 96,000. The note was called on 06 OCT.' },
          { id: 'debt-body-2', kind: 'paragraph', text: 'Two equal settlements of 48,000 will close the marker. The first was received on 13 OCT from a third-party account.' },
          { id: 'debt-quote-1', kind: 'quote', text: 'Employment disclosure will follow if the balance is unpaid after 15 OCT.' },
        ],
      },
      {
        id: 'debt-page-2',
        label: 'PAGE 2 OF 2',
        blocks: [
          { id: 'debt-heading-2', kind: 'heading', text: 'BORROWER CONDITIONS' },
          { id: 'debt-body-3', kind: 'paragraph', text: 'The borrower declared no secondary income and is contractually required to report the debt to his employer’s security vetting office.' },
          { id: 'debt-body-4', kind: 'paragraph', text: 'No such declaration appears in the Hartwell vetting file.' },
        ],
      },
    ],
  },
  {
    id: 'evidence-doc-lounge-call-record',
    type: 'document',
    title: 'Auction Lounge extension call record',
    source: 'Crown & Row telephone system',
    summary:
      'The lounge niche extension carried one continuous outbound call across the entire substitution window.',
    capturedAtLabel: 'EXPORTED 22:44 · 14 OCT',
    tags: ['digital', 'alibi', 'auction-lounge'],
    documentType: 'CALL DETAIL RECORD / EXT 214',
    author: 'Crown & Row telephony export',
    pages: [
      {
        id: 'lounge-cdr-page-1',
        label: 'PAGE 1 OF 1',
        blocks: [
          { id: 'lounge-cdr-heading-1', kind: 'heading', text: 'EXTENSION 214 — TELEPHONE NICHE' },
          { id: 'lounge-cdr-body-1', kind: 'paragraph', text: 'Handset lifted 21:14:06. Outbound call to a Catalogue Seven principal line. Call cleared 21:22:58. No hold, transfer, or disconnection is recorded.' },
          { id: 'lounge-cdr-body-2', kind: 'paragraph', text: 'The niche handset is corded and mounted inside the recess. The line drops immediately if the handset leaves the cradle area.' },
          { id: 'lounge-cdr-body-3', kind: 'paragraph', text: 'The niche has no second exit; the lounge camera covers its only doorway and records no departure between 21:14 and 21:23.' },
          { id: 'lounge-cdr-quote-1', kind: 'quote', text: 'The occupant of the niche could speak to a buyer, but could not walk to Gallery Four.' },
        ],
      },
    ],
  },

  // RECEIPTS AND TRANSACTION RECORDS
  {
    id: 'evidence-receipt-prism-replica',
    type: 'receipt',
    title: 'Prism Props fabrication receipt',
    source: 'Prism Props order archive',
    summary: 'A museum-grade 42.2-carat replica was collected under the Northline Events account.',
    capturedAtLabel: 'ISSUED 16:42 · 13 OCT',
    tags: ['digital', 'replica', 'purchase'],
    merchant: 'PRISM PROPS & FACSIMILES',
    addressLines: ['14 Foundry Mews', 'Lydon Arts Quarter'],
    issuedAtLabel: '13 OCT · 16:42',
    lines: [
      { id: 'prism-line-1', description: 'Optical crystal stone / 42.2 ct profile', quantity: 1, amountLabel: '2,840.00' },
      { id: 'prism-line-2', description: 'Asterion archival scan match', quantity: 1, amountLabel: '760.00' },
      { id: 'prism-line-3', description: 'Five-point workshop micro-mark', quantity: 1, amountLabel: '0.00' },
    ],
    subtotalLabel: '3,600.00',
    taxLabel: '288.00',
    totalLabel: '3,888.00',
    paymentLabel: 'NORTHLINE EVENTS / TOKEN 0441',
    referenceLabel: 'ORDER PP-4417',
  },
  {
    id: 'evidence-receipt-auction-wine',
    type: 'receipt',
    title: 'Auction Lounge tasting ticket',
    source: 'Crown & Row hospitality terminal',
    summary: 'Elias Ward’s personalized tasting account opens at 21:10 and closes at 21:23, with an unobserved interval.',
    capturedAtLabel: '21:23 · 14 OCT',
    tags: ['digital', 'alibi', 'auction-lounge'],
    merchant: 'CROWN & ROW / HARTWELL LOUNGE',
    addressLines: ['Private Appraiser Table', 'Grand Rotunda West'],
    issuedAtLabel: '14 OCT · 21:23',
    lines: [
      { id: 'wine-line-1', description: 'Appraiser flight / table 3', quantity: 1, amountLabel: 'HOSTED' },
      { id: 'wine-line-2', description: 'Sparkling water', quantity: 1, amountLabel: 'HOSTED' },
    ],
    subtotalLabel: '0.00',
    totalLabel: '0.00',
    paymentLabel: 'GUEST: ELIAS WARD',
    referenceLabel: 'OPEN 21:10:22 / CLOSE 21:23:51',
  },
  {
    id: 'evidence-receipt-julian-restaurant',
    type: 'receipt',
    title: 'Julian Rook hospitality charge',
    source: 'Hartwell gala point-of-sale',
    summary: 'A conspicuous cash advance request supports financial pressure but predates the theft window.',
    capturedAtLabel: '20:41 · 14 OCT',
    tags: ['digital', 'red-herring', 'financial'],
    merchant: 'HARTWELL GALA HOSPITALITY',
    addressLines: ['Auction Lounge', 'Host Table 2'],
    issuedAtLabel: '14 OCT · 20:41',
    lines: [
      { id: 'julian-receipt-line-1', description: 'Private table service', quantity: 1, amountLabel: '240.00' },
      { id: 'julian-receipt-line-2', description: 'Cash advance request — declined', quantity: 1, amountLabel: '5,000.00' },
    ],
    subtotalLabel: '240.00',
    totalLabel: '240.00',
    paymentLabel: 'ROOK HOUSE CARD / DECLINED THEN HOSTED',
    referenceLabel: 'TABLE J-02',
  },
  {
    id: 'evidence-receipt-transfer',
    type: 'receipt',
    title: 'Northline transfer confirmation',
    source: 'Recovered payment wallet export',
    summary: 'A second payment from Ward’s Northline account reaches a wallet labeled AC Reserve after the gallery lockdown.',
    capturedAtLabel: '22:02 · 14 OCT',
    tags: ['digital', 'payment', 'relationship'],
    merchant: 'MERIDIAN PRIVATE TRANSFER',
    addressLines: ['Encrypted settlement record', 'Compliance copy'],
    issuedAtLabel: '14 OCT · 22:02',
    lines: [
      { id: 'transfer-line-1', description: 'Northline Events → AC Reserve', quantity: 1, amountLabel: '48,000.00' },
      { id: 'transfer-line-2', description: 'Memo: second half / blue star', quantity: 1, amountLabel: '0.00' },
    ],
    subtotalLabel: '48,000.00',
    totalLabel: '48,000.00',
    paymentLabel: 'SETTLED / TWO-KEY AUTH',
    referenceLabel: 'MPT-1410-2202',
  },
  {
    id: 'evidence-receipt-locker-service',
    type: 'receipt',
    title: 'Locker B service chit',
    source: 'Loading Dock maintenance kiosk',
    summary: 'Security work order SC-204 moves radio R-17 to Locker B and issues a temporary B-tag to East Command.',
    capturedAtLabel: '09:18 · 14 OCT',
    tags: ['physical', 'locker', 'radio'],
    merchant: 'HARTWELL FACILITIES KIOSK',
    addressLines: ['Loading Dock', 'Equipment Cage'],
    issuedAtLabel: '14 OCT · 09:18',
    lines: [
      { id: 'locker-line-1', description: 'Radio R-17 / retain battery shell', quantity: 1, amountLabel: 'N/C' },
      { id: 'locker-line-2', description: 'Temporary Locker B key tag', quantity: 1, amountLabel: 'N/C' },
    ],
    subtotalLabel: '0.00',
    totalLabel: '0.00',
    paymentLabel: 'WORK ORDER SC-204',
    referenceLabel: 'REQUESTOR: EAST SECURITY COMMAND',
  },

  // MESSAGE THREADS (5)
  {
    id: 'evidence-message-adrian-elias',
    type: 'message',
    title: '“Blue star” encrypted thread',
    source: 'Recovered Cross handset partition',
    summary: 'Coded planning messages connect Cross, Ward, the replica, and a post-gala handoff.',
    capturedAtLabel: 'RECOVERED 22:26 · 14 OCT',
    tags: ['digital', 'relationship', 'planning'],
    platform: 'Cipherline',
    conversationTitle: 'A.C. / E.W. — archived channel',
    participants: [
      { id: 'adrian-thread-cross', displayName: 'A.C.', handle: '@eastwatch', isDeviceOwner: true },
      { id: 'adrian-thread-ward', displayName: 'E.W.', handle: '@catalogue7' },
    ],
    messages: [
      { id: 'adrian-elias-msg-1', senderId: 'adrian-thread-ward', sentAtLabel: '13 OCT · 16:51', body: 'The glass star is collected. Five points under the rim, as agreed.', status: 'read' },
      { id: 'adrian-elias-msg-2', senderId: 'adrian-thread-cross', sentAtLabel: '13 OCT · 16:54', body: 'Keep Northline clean. Tomorrow the room blinks at seventeen past.', status: 'read' },
      { id: 'adrian-elias-msg-3', senderId: 'adrian-thread-ward', sentAtLabel: '14 OCT · 20:48', body: 'Buyer holds until midnight. Half already covered your marker.', status: 'read' },
      { id: 'adrian-elias-msg-4', senderId: 'adrian-thread-cross', sentAtLabel: '14 OCT · 21:22', body: 'Blue star is asleep with the dead sets. Doors locked early.', status: 'delivered' },
      { id: 'adrian-elias-msg-5', senderId: 'adrian-thread-ward', sentAtLabel: '14 OCT · 21:23', body: 'Do not move it. I will trigger the second half.', status: 'read' },
    ],
  },
  {
    id: 'evidence-message-mara-nia',
    type: 'message',
    title: 'Bell–Okafor source thread',
    source: 'Okafor press device export',
    summary: 'The thread explains their secrecy and records a live call spanning the theft window.',
    tags: ['digital', 'alibi', 'red-herring'],
    platform: 'QuietWire',
    conversationTitle: 'Source M / Nia',
    participants: [
      { id: 'mara-nia-mara', displayName: 'Source M' },
      { id: 'mara-nia-nia', displayName: 'Nia Okafor', isDeviceOwner: true },
    ],
    messages: [
      { id: 'mara-nia-msg-1', senderId: 'mara-nia-mara', sentAtLabel: '20:59', body: 'The plinth drifted again. I have the logged readings, not the stone.', status: 'read' },
      { id: 'mara-nia-msg-2', senderId: 'mara-nia-nia', sentAtLabel: '21:07', body: 'Call me from the lab when the quartet starts. I only need the climate record.', status: 'read' },
      { id: 'mara-nia-msg-3', senderId: 'mara-nia-mara', sentAtLabel: '21:11', body: 'Calling now. RM-2 is running.', status: 'read' },
      { id: 'mara-nia-msg-4', senderId: 'mara-nia-nia', sentAtLabel: '21:24', body: 'Got it. Stay there until I confirm the file copied.', status: 'read' },
    ],
  },
  {
    id: 'evidence-message-julian-creditor',
    type: 'message',
    title: 'Rook creditor thread',
    source: 'Julian Rook handset warrant export',
    summary: 'Severe debt supplies motive, but call metadata and terrace footage support his location.',
    tags: ['digital', 'financial', 'red-herring'],
    platform: 'Standard Messages',
    conversationTitle: 'Julian / H. Vale',
    participants: [
      { id: 'julian-thread-rook', displayName: 'Julian Rook', isDeviceOwner: true },
      { id: 'julian-thread-vale', displayName: 'Hector Vale' },
    ],
    messages: [
      { id: 'julian-msg-1', senderId: 'julian-thread-vale', sentAtLabel: '20:36', body: 'Midnight is the extension. After that the note is called.', status: 'read' },
      { id: 'julian-msg-2', senderId: 'julian-thread-rook', sentAtLabel: '21:12', body: 'Calling from the roof. You will have a proposal, not the family stone.', status: 'read' },
      { id: 'julian-msg-3', senderId: 'julian-thread-vale', sentAtLabel: '21:24', body: 'Fourteen minutes. Proposal rejected. Monday, then.', status: 'read' },
    ],
  },
  {
    id: 'evidence-message-celeste-board',
    type: 'message',
    title: 'Museum board emergency thread',
    source: 'Hartwell board archive',
    summary: 'Vane pushed for increased insurance and threatened to cancel the gala over climate risk.',
    tags: ['digital', 'insurance', 'red-herring'],
    platform: 'Hartwell BoardLine',
    conversationTitle: 'Asterion oversight',
    participants: [
      { id: 'board-celeste', displayName: 'Celeste Vane', isDeviceOwner: true },
      { id: 'board-chair', displayName: 'Board Chair Imogen Hart' },
    ],
    messages: [
      { id: 'celeste-board-msg-1', senderId: 'board-celeste', sentAtLabel: '12 OCT · 18:06', body: 'If the humidity drift repeats, I will close the gallery regardless of donor pressure.', status: 'read' },
      { id: 'celeste-board-msg-2', senderId: 'board-chair', sentAtLabel: '12 OCT · 18:19', body: 'The rider is approved. Do not create a public panic before the gala.', status: 'read' },
      { id: 'celeste-board-msg-3', senderId: 'board-celeste', sentAtLabel: '14 OCT · 21:26', body: 'Seal every exit. The displayed stone is not the Asterion.', status: 'delivered' },
    ],
  },
  {
    id: 'evidence-message-gala-staff',
    type: 'message',
    title: 'Gala operations channel',
    source: 'Hartwell staff dispatch archive',
    summary: 'Staff messages timestamp the power test, alarm, loading lockdown, and a delayed service van.',
    tags: ['digital', 'timeline', 'operations'],
    platform: 'Hartwell Dispatch',
    conversationTitle: 'GALA OPS / ALL TEAMS',
    participants: [
      { id: 'ops-control', displayName: 'Control', isDeviceOwner: true },
      { id: 'ops-facilities', displayName: 'Facilities' },
      { id: 'ops-loading', displayName: 'Loading Dock' },
    ],
    messages: [
      { id: 'ops-msg-1', senderId: 'ops-control', sentAtLabel: '21:16', body: 'Generator transfer test at 21:17. Ninety seconds. No public announcement.', status: 'read' },
      { id: 'ops-msg-2', senderId: 'ops-facilities', sentAtLabel: '21:18', body: 'Transfer clean. Gallery Four battery remained online.', status: 'read' },
      { id: 'ops-msg-3', senderId: 'ops-control', sentAtLabel: '21:26', body: 'Code amber. Hold all doors and loading access.', status: 'read' },
      { id: 'ops-msg-4', senderId: 'ops-loading', sentAtLabel: '21:31', body: 'Dock cage sealed. Northline pickup van remains outside perimeter.', status: 'read' },
    ],
  },

  // EMAILS (7)
  {
    id: 'evidence-email-security-roster',
    type: 'email',
    title: 'Gala security duty roster',
    source: 'Hartwell SecureMail',
    summary: 'Cross assigned himself east command, credential administration, and bypass-key custody.',
    tags: ['digital', 'access', 'roster'],
    from: { name: 'Adrian Cross', address: 'a.cross@hartwell.invalid' },
    to: [{ name: 'Gala Security Team', address: 'gala-security@hartwell.invalid' }],
    sentAtLabel: '14 OCT · 15:32',
    subject: 'FINAL: Midnight Gallery assignments',
    body: [
      { id: 'roster-email-heading', kind: 'heading', text: 'EAST COMMAND' },
      { id: 'roster-email-body-1', kind: 'paragraph', text: 'A. Cross — command desk, credential admin AS-01, master bypass set K-2.' },
      { id: 'roster-email-body-2', kind: 'paragraph', text: 'No relief scheduled 20:00–22:00. Radio checks at quarter-hour intervals.' },
    ],
    attachmentEvidenceIds: ['evidence-photo-keyring'],
  },
  {
    id: 'evidence-email-badge-alert',
    type: 'email',
    title: 'Suppressed duplicate-credential alert',
    source: 'Hartwell Access Control mailbox',
    summary: 'An automatic warning identifies a duplicate of MC-04 and records manual acknowledgment at AS-01.',
    tags: ['digital', 'credential', 'alert'],
    from: { name: 'Access Control Daemon', address: 'access-daemon@hartwell.invalid' },
    to: [{ name: 'Security Alerts', address: 'security-alerts@hartwell.invalid' }],
    sentAtLabel: '14 OCT · 20:52:26',
    subject: 'HIGH: duplicate legacy profile MC-04',
    body: [
      { id: 'badge-email-body-1', kind: 'paragraph', text: 'Replacement token DT-884 encoded from revoked profile MC-04 at terminal AS-01.' },
      { id: 'badge-email-body-2', kind: 'paragraph', text: 'Risk: original holder not present for identity verification. Alert acknowledged by current administrator session.' },
      { id: 'badge-email-body-3', kind: 'paragraph', text: 'Original physical credential serial MC-04-P remains archived in Restoration Office safe.' },
    ],
    attachmentEvidenceIds: ['evidence-doc-admin-audit'],
  },
  {
    id: 'evidence-email-insurance-rider',
    type: 'email',
    title: 'Asterion insurance rider approval',
    source: 'Hartwell Executive Mail',
    summary: 'The museum’s payout was doubled shortly before the gala, creating an apparent institutional motive.',
    tags: ['digital', 'insurance', 'red-herring'],
    from: { name: 'Imogen Hart', address: 'chair@hartwell.invalid' },
    to: [{ name: 'Celeste Vane', address: 'director@hartwell.invalid' }],
    sentAtLabel: '12 OCT · 18:17',
    subject: 'RE: climate exposure rider',
    body: [
      { id: 'insurance-email-body-1', kind: 'paragraph', text: 'Underwriters approved the temporary increase to 80 million for the gala period.' },
      { id: 'insurance-email-body-2', kind: 'paragraph', text: 'The rider names the Rook Trust as loss payee. Hartwell receives no proceeds beyond documented closure costs.' },
    ],
    attachmentEvidenceIds: [],
  },
  {
    id: 'evidence-email-replica-order',
    type: 'email',
    title: 'Northline replica pickup confirmation',
    source: 'Prism Props order mailbox',
    summary: 'The commission specifies the Asterion scan and instructs staff to release the replica to an East Command courier.',
    tags: ['digital', 'replica', 'planning'],
    from: { name: 'Prism Props Dispatch', address: 'dispatch@prism-props.invalid' },
    to: [{ name: 'Northline Events', address: 'orders@northline.invalid' }],
    sentAtLabel: '13 OCT · 15:58',
    subject: 'PP-4417 ready for controlled pickup',
    body: [
      { id: 'replica-email-body-1', kind: 'paragraph', text: 'Your 42.2 ct Asterion-profile optical replica is ready. Workshop mark: five-point star below girdle.' },
      { id: 'replica-email-body-2', kind: 'paragraph', text: 'Release instruction amended by account holder: courier phrase EAST COMMAND. No photo identification requested.' },
    ],
    attachmentEvidenceIds: ['evidence-receipt-prism-replica'],
  },
  {
    id: 'evidence-email-restoration-report',
    type: 'email',
    title: 'Unresolved plinth climate warning',
    source: 'Hartwell Conservation Mail',
    summary: 'Bell objected to display conditions; the argument creates motive but also explains her contact with the press.',
    tags: ['digital', 'climate', 'red-herring'],
    from: { name: 'Mara Bell', address: 'm.bell@hartwell.invalid' },
    to: [{ name: 'Celeste Vane', address: 'director@hartwell.invalid' }],
    cc: [{ name: 'Facilities', address: 'facilities@hartwell.invalid' }],
    sentAtLabel: '14 OCT · 17:06',
    subject: 'Do not open Gallery Four without stabilizing P4',
    body: [
      { id: 'restoration-email-body-1', kind: 'paragraph', text: 'P4 drifted 3.2 percent above the loan limit. I recommend delaying the public display.' },
      { id: 'restoration-email-body-2', kind: 'paragraph', text: 'I have moved my calibration session to 21:08 and will preserve the live RM-2 logs.' },
      { id: 'restoration-email-quote-1', kind: 'quote', text: 'If the board ignores the record, I will document that decision elsewhere.' },
    ],
    attachmentEvidenceIds: ['evidence-doc-restoration-log'],
  },
  {
    id: 'evidence-email-elias-consignment',
    type: 'email',
    title: 'Unlisted stone consignment inquiry',
    source: 'Ward & Vale recovered drafts',
    summary: 'Ward sought a buyer for an undocumented forty-two-carat stone using the same blue-star phrase found in messages.',
    tags: ['digital', 'buyer', 'planning'],
    from: { name: 'Elias Ward', address: 'e.ward@ward-vale.invalid' },
    to: [{ name: 'Private Catalogue Seven', address: 'principal@catalogue-seven.invalid' }],
    sentAtLabel: '11 OCT · 09:14',
    subject: 'Off-catalogue inquiry / blue star',
    body: [
      { id: 'consignment-email-body-1', kind: 'paragraph', text: 'A colorless 42 ct stone may become available without public provenance after the Hartwell event.' },
      { id: 'consignment-email-body-2', kind: 'paragraph', text: 'Settlement should route through Northline. Inspection only after the stone clears the city.' },
      { id: 'consignment-email-redaction', kind: 'redaction', characterCount: 42 },
    ],
    attachmentEvidenceIds: ['evidence-receipt-transfer'],
  },
  {
    id: 'evidence-email-power-test',
    type: 'email',
    title: 'Generator-transfer test notice',
    source: 'Hartwell Facilities Mail',
    summary: 'A planned ninety-second power transfer was known to Security Command and did not disable the plinth.',
    tags: ['digital', 'timeline', 'opportunity'],
    from: { name: 'Facilities Control', address: 'control@hartwell.invalid' },
    to: [
      { name: 'Adrian Cross', address: 'a.cross@hartwell.invalid' },
      { name: 'Celeste Vane', address: 'director@hartwell.invalid' },
    ],
    sentAtLabel: '14 OCT · 13:40',
    subject: '21:17 generator transfer — final notice',
    body: [
      { id: 'power-email-body-1', kind: 'paragraph', text: 'Transfer begins 21:17 and should last no longer than ninety seconds.' },
      { id: 'power-email-body-2', kind: 'paragraph', text: 'Camera control may display a synchronization warning. Gallery Four plinth remains on isolated battery power.' },
    ],
    attachmentEvidenceIds: [],
  },

  // CCTV SOURCES (4)
  {
    id: 'evidence-cctv-gallery',
    type: 'cctv',
    title: 'Gallery Four overhead feed',
    source: 'CAM-G4 / recorder mirror',
    summary: 'The display appears untouched, but visitor motion repeats during the generator transfer.',
    tags: ['digital', 'camera', 'replay'],
    cameraLabel: 'CAM-G4 / ASTERION PLINTH',
    recordedAtLabel: '21:16:40–21:21:20 · 14 OCT',
    durationSeconds: 280,
    video: {
      assetId: 'case001-cctv-gallery-video',
      altText: 'Overhead CCTV view of a museum display and passing gala guests.',
      width: 1920,
      height: 1080,
    },
    poster: {
      assetId: 'case001-cctv-gallery-poster',
      altText: 'Monochrome overhead view of the Asterion display.',
      width: 1600,
      height: 900,
    },
    markers: [
      { id: 'gallery-marker-transfer', offsetSeconds: 20, label: 'TRANSFER' },
      { id: 'gallery-marker-repeat', offsetSeconds: 51, label: 'REPEATED GUEST' },
      { id: 'gallery-marker-live', offsetSeconds: 264, label: 'LIVE HASH' },
    ],
    transcript: [
      { id: 'gallery-transcript-1', kind: 'paragraph', text: 'No camera audio. Control metadata reports LIVE throughout.' },
    ],
  },
  {
    id: 'evidence-cctv-east-corridor',
    type: 'cctv',
    title: 'East service corridor infrared feed',
    source: 'CAM-E2 / local SD recovery',
    summary: 'A security-uniform silhouette travels to and from Gallery Four while the central recorder omits the source.',
    tags: ['digital', 'camera', 'service-route'],
    cameraLabel: 'CAM-E2 / EAST SERVICE',
    recordedAtLabel: '21:11:40–21:22:40 · 14 OCT',
    durationSeconds: 660,
    video: {
      assetId: 'case001-cctv-corridor-video',
      altText: 'Infrared CCTV view down a narrow museum service corridor.',
      width: 1920,
      height: 1080,
    },
    poster: {
      assetId: 'case001-cctv-corridor-poster',
      altText: 'Infrared silhouette in a museum service corridor.',
      width: 1600,
      height: 900,
    },
    markers: [
      { id: 'corridor-marker-out', offsetSeconds: 31, label: 'LEAVES ANNEX' },
      { id: 'corridor-marker-gallery', offsetSeconds: 382, label: 'TO GALLERY' },
      { id: 'corridor-marker-return', offsetSeconds: 568, label: 'RETURNS' },
    ],
    transcript: [
      { id: 'corridor-transcript-1', kind: 'paragraph', text: 'No audio. Reflective shoulder band and command-radio antenna are visible.' },
    ],
  },
  {
    id: 'evidence-cctv-roof-terrace',
    type: 'cctv',
    title: 'Roof Terrace door camera',
    source: 'CAM-R1 / event archive',
    summary: 'Julian Rook remains visible on a phone call throughout the exchange window.',
    tags: ['digital', 'camera', 'alibi'],
    cameraLabel: 'CAM-R1 / ROOF TERRACE',
    recordedAtLabel: '21:12:30–21:24:40 · 14 OCT',
    durationSeconds: 730,
    video: {
      assetId: 'case001-cctv-terrace-video',
      altText: 'Night CCTV view of a man speaking on a museum roof terrace.',
      width: 1920,
      height: 1080,
    },
    poster: {
      assetId: 'case001-cctv-terrace-poster',
      altText: 'Julian Rook standing alone on a roof terrace.',
      width: 1600,
      height: 900,
    },
    markers: [
      { id: 'terrace-marker-entry', offsetSeconds: 30, label: 'ROOK ENTERS' },
      { id: 'terrace-marker-transfer', offsetSeconds: 270, label: '21:17' },
      { id: 'terrace-marker-exit', offsetSeconds: 711, label: 'CALL ENDS' },
    ],
    transcript: [
      { id: 'terrace-transcript-1', kind: 'quote', text: 'You will have a proposal, not the family stone.' },
    ],
  },
  {
    id: 'evidence-cctv-auction-lounge',
    type: 'cctv',
    title: 'Auction Lounge hospitality feed',
    source: 'CAM-A3 / Crown & Row',
    summary: 'Ward is recorded at 21:13 and 21:23 but spends the intervening minutes in an unmonitored telephone niche.',
    tags: ['digital', 'camera', 'partial-alibi'],
    cameraLabel: 'CAM-A3 / AUCTION LOUNGE',
    recordedAtLabel: '21:09:30–21:24:30 · 14 OCT',
    durationSeconds: 900,
    video: {
      assetId: 'case001-cctv-auction-video',
      altText: 'CCTV view of a private auction lounge and tasting table.',
      width: 1920,
      height: 1080,
    },
    poster: {
      assetId: 'case001-cctv-auction-poster',
      altText: 'Elias Ward near a private lounge tasting table.',
      width: 1600,
      height: 900,
    },
    markers: [
      { id: 'auction-marker-visible', offsetSeconds: 214, label: 'WARD VISIBLE' },
      { id: 'auction-marker-niche', offsetSeconds: 279, label: 'ENTERS NICHE' },
      { id: 'auction-marker-return', offsetSeconds: 831, label: 'RETURNS' },
    ],
    transcript: [
      { id: 'auction-transcript-1', kind: 'paragraph', text: 'Ambient room audio only. The telephone niche is outside frame.' },
    ],
  },

  // LOCAL WEB CAPTURES (6)
  {
    id: 'evidence-web-gala-schedule',
    type: 'webpage',
    title: 'Midnight Gallery event schedule',
    source: 'Hartwell Museum local archive',
    summary: 'The published program establishes public movements and the quartet cue around the theft window.',
    tags: ['digital', 'timeline', 'museum'],
    siteName: 'Hartwell Museum',
    displayUrl: 'hartwell-museum.invalid/events/midnight-gallery',
    headline: 'Midnight Gallery — Patron Evening',
    byline: 'Hartwell Events Office',
    publishedAtLabel: '14 OCT · 09:00',
    body: [
      { id: 'gala-web-heading-1', kind: 'heading', text: 'PROGRAM' },
      { id: 'gala-web-body-1', kind: 'paragraph', text: '20:45 Curator remarks · 21:14 Rotunda quartet introduction · 21:30 Asterion private viewing.' },
      { id: 'gala-web-body-2', kind: 'paragraph', text: 'Gallery Four stays closed behind the east arcade screen until the scheduled private viewing. No guest route passes the display before 21:30.' },
    ],
    capturedAtLabel: 'LOCAL CAPTURE · 21:38',
  },
  {
    id: 'evidence-web-vane-finances',
    type: 'webpage',
    title: 'Rook trust faces liquidity questions',
    source: 'The Lydon Ledger local edition',
    summary: 'The article publicly documents Julian Rook’s debt and the trust restrictions on the Asterion.',
    tags: ['digital', 'financial', 'red-herring'],
    siteName: 'The Lydon Ledger',
    displayUrl: 'lydon-ledger.invalid/culture/rook-trust',
    headline: 'Rook heir rich in objects, short on cash',
    byline: 'Amal Byrne',
    publishedAtLabel: '10 OCT · 07:20',
    body: [
      { id: 'finances-web-body-1', kind: 'paragraph', text: 'Court filings show short-term liabilities exceeding liquid assets controlled by Julian Rook.' },
      { id: 'finances-web-body-2', kind: 'paragraph', text: 'The Asterion cannot be sold without trustee consent and remains insured to the family trust.' },
      { id: 'finances-web-quote-1', kind: 'quote', text: 'An obvious motive is not the same as an available method.' },
    ],
    capturedAtLabel: 'LOCAL CAPTURE · 21:42',
  },
  {
    id: 'evidence-web-prism-catalog',
    type: 'webpage',
    title: 'Prism archival facsimile listing',
    source: 'Prism Props local order catalog',
    summary: 'The listing explains the five-point workshop mark found on all Prism optical replicas.',
    tags: ['digital', 'replica', 'vendor'],
    siteName: 'Prism Props',
    displayUrl: 'prism-props.invalid/catalog/archival-stones',
    headline: 'Archival gemstone facsimiles',
    byline: 'Workshop catalogue',
    body: [
      { id: 'prism-web-body-1', kind: 'paragraph', text: 'Optical replicas are cut from supplied scans and marked below the girdle for ethical identification.' },
      { id: 'prism-web-body-2', kind: 'paragraph', text: 'Current workshop batch mark: a five-point star measuring 0.4 mm.' },
    ],
    capturedAtLabel: 'LOCAL CAPTURE · 22:06',
  },
  {
    id: 'evidence-web-nia-livestream',
    type: 'webpage',
    title: 'Okafor field recording archive',
    source: 'Nia Field Notes local mirror',
    summary: 'An unedited recording and signed waveform place Okafor in the Press Alcove through the theft window.',
    tags: ['digital', 'alibi', 'press'],
    siteName: 'Nia Field Notes',
    displayUrl: 'nia-fieldnotes.invalid/archive/hartwell-take-3',
    headline: 'Hartwell field take 3 — uncut',
    byline: 'Nia Okafor',
    publishedAtLabel: '14 OCT · 21:22',
    body: [
      { id: 'nia-web-body-1', kind: 'paragraph', text: 'Recording starts 21:16:02 and ends 21:22:18. Rotunda quartet and stage announcements remain continuous.' },
      { id: 'nia-web-body-2', kind: 'paragraph', text: 'Encoder signature matches the press-alcove device assigned to Okafor.' },
    ],
    capturedAtLabel: 'LOCAL CAPTURE · 21:47',
  },
  {
    id: 'evidence-web-channel8-gallery',
    type: 'webpage',
    title: 'Channel Eight gala stills',
    source: 'Channel Eight local newsroom node',
    summary: 'Signed broadcast stills repeatedly place Vane in the Rotunda during the critical interval.',
    tags: ['digital', 'alibi', 'broadcast'],
    siteName: 'Channel Eight Lydon',
    displayUrl: 'channel8-lydon.invalid/live/hartwell-gala',
    headline: 'Inside Hartwell’s Midnight Gallery gala',
    byline: 'Channel Eight Culture Desk',
    publishedAtLabel: '14 OCT · LIVE ARCHIVE',
    body: [
      { id: 'channel-web-body-1', kind: 'paragraph', text: 'Frames at 21:14:36, 21:17:08, and 21:20:41 include Dr. Celeste Vane beside the donor dais.' },
      { id: 'channel-web-body-2', kind: 'paragraph', text: 'Field encoder signature C8-LY-4 verified.' },
    ],
    capturedAtLabel: 'LOCAL CAPTURE · 21:44',
  },
  {
    id: 'evidence-web-citythread-van',
    type: 'webpage',
    title: 'Service-lane van thread',
    source: 'Lydon Neighbourwire local archive',
    summary: 'A witness noticed a Northline van, but it remained outside the sealed dock and never entered the museum.',
    tags: ['digital', 'vehicle', 'red-herring'],
    siteName: 'Lydon Neighbourwire',
    displayUrl: 'lydon-neighbourwire.invalid/thread/hartwell-van',
    headline: 'Anyone else see the blank van behind Hartwell?',
    byline: '@NightTram',
    publishedAtLabel: '14 OCT · 21:36',
    body: [
      { id: 'van-web-body-1', kind: 'paragraph', text: 'White Northline Events van arrived around 21:20 and waited beyond the loading gate.' },
      { id: 'van-web-body-2', kind: 'paragraph', text: 'Reply from @DockWindow: Gate never opened. Van left after police arrived.' },
    ],
    capturedAtLabel: 'LOCAL CAPTURE · 21:52',
  },

  // INTERVIEW STATEMENTS (6)
  {
    id: 'evidence-statement-celeste',
    type: 'statement',
    title: 'Statement of Dr. Celeste Vane',
    source: 'Interview Room A',
    summary: 'Vane describes discovering the replica and acknowledges the insurance increase and conflict with Bell.',
    tags: ['statement', 'alibi', 'insurance'],
    speakerName: 'Dr. Celeste Vane',
    speakerRole: 'Museum director',
    recordedAtLabel: '22:04 · 14 OCT',
    locationLabel: 'Hartwell Interview Room A',
    paragraphs: [
      { id: 'celeste-statement-1', kind: 'quote', text: 'I was beside the donor dais from the quartet introduction until I went to Gallery Four at 21:25.' },
      { id: 'celeste-statement-2', kind: 'paragraph', text: 'The stone looked too clean. The Asterion has a feather under the crown; this one had none.' },
      { id: 'celeste-statement-3', kind: 'paragraph', text: 'I requested the insurance rider because Mara documented a climate risk. Hartwell is not the loss payee.' },
      { id: 'celeste-statement-4', kind: 'quote', text: 'Mara and I argued, but she was right to preserve the instrument record.' },
    ],
    signedBy: 'Celeste Vane',
  },
  {
    id: 'evidence-statement-adrian',
    type: 'statement',
    title: 'Statement of Adrian Cross',
    source: 'Interview Room B',
    summary: 'Cross claims continuous desk presence and attributes the panel entry to Bell’s credential.',
    tags: ['statement', 'alibi', 'contradiction'],
    speakerName: 'Adrian Cross',
    speakerRole: 'Head of security',
    recordedAtLabel: '22:09 · 14 OCT',
    locationLabel: 'Hartwell Interview Room B',
    paragraphs: [
      { id: 'adrian-statement-1', kind: 'quote', text: 'I did not leave East Command between 20:50 and lockdown. The console record will show my checks.' },
      { id: 'adrian-statement-2', kind: 'paragraph', text: 'The access event is MC-04. Mara Bell owned that credential, not me.' },
      { id: 'adrian-statement-3', kind: 'quote', text: 'Ward is an appraiser I have met in passing. There is no private relationship.' },
      { id: 'adrian-statement-4', kind: 'paragraph', text: 'The triangular key remained on my issued ring.' },
    ],
    signedBy: 'Adrian Cross',
  },
  {
    id: 'evidence-statement-mara',
    type: 'statement',
    title: 'Statement of Mara Bell',
    source: 'Restoration Lab interview',
    summary: 'Bell admits leaking climate data but denies possessing the revoked credential used at the panel.',
    tags: ['statement', 'alibi', 'press-source'],
    speakerName: 'Mara Bell',
    speakerRole: 'Senior conservator',
    recordedAtLabel: '21:56 · 14 OCT',
    locationLabel: 'Restoration Laboratory',
    paragraphs: [
      { id: 'mara-statement-1', kind: 'quote', text: 'MC-04 was revoked months ago and the physical card is sealed in the office safe.' },
      { id: 'mara-statement-2', kind: 'paragraph', text: 'I called Nia because the board ignored the humidity drift. That was the secret, not a plan to touch the diamond.' },
      { id: 'mara-statement-3', kind: 'paragraph', text: 'RM-2 autosaves every stage movement. I was using it from 21:09 until 21:24.' },
      { id: 'mara-statement-4', kind: 'quote', text: 'The replica’s star mark is a workshop signature. Search theatrical prop vendors.' },
    ],
    signedBy: 'Mara Bell',
  },
  {
    id: 'evidence-statement-julian',
    type: 'statement',
    title: 'Statement of Julian Rook',
    source: 'Interview Room C',
    summary: 'Rook acknowledges his debts but says stealing the trust asset would not release its value to him.',
    tags: ['statement', 'alibi', 'financial'],
    speakerName: 'Julian Rook',
    speakerRole: 'Rook trust beneficiary',
    recordedAtLabel: '22:19 · 14 OCT',
    locationLabel: 'Hartwell Interview Room C',
    paragraphs: [
      { id: 'julian-statement-1', kind: 'quote', text: 'Yes, I owe money. No, I cannot sell a trust stone whose inclusion map is known worldwide.' },
      { id: 'julian-statement-2', kind: 'paragraph', text: 'I went to the roof at 21:13 and stayed on the call until roughly 21:24.' },
      { id: 'julian-statement-3', kind: 'paragraph', text: 'Ward appraised family pieces before. He refused to discuss the Asterion because of the trust restriction.' },
    ],
    signedBy: 'Julian Rook',
  },
  {
    id: 'evidence-statement-nia',
    type: 'statement',
    title: 'Statement of Nia Okafor',
    source: 'Press Alcove interview',
    summary: 'Okafor admits recording without approval and identifies Bell as her climate-safety source.',
    tags: ['statement', 'alibi', 'press'],
    speakerName: 'Nia Okafor',
    speakerRole: 'Investigative reporter',
    recordedAtLabel: '21:51 · 14 OCT',
    locationLabel: 'Press Alcove',
    paragraphs: [
      { id: 'nia-statement-1', kind: 'quote', text: 'I recorded the whole take from 21:16 to 21:22. The raw file is on my local mirror.' },
      { id: 'nia-statement-2', kind: 'paragraph', text: 'Mara was my source on climate negligence. She was talking to me from the lab during the outage.' },
      { id: 'nia-statement-3', kind: 'paragraph', text: 'Cross tried to cancel my credential after my last security story. I expected him to watch me, not the other way around.' },
    ],
    signedBy: 'Nia Okafor',
  },
  {
    id: 'evidence-statement-elias',
    type: 'statement',
    title: 'Statement of Elias Ward',
    source: 'Auction Lounge interview',
    summary: 'Ward claims continuous lounge presence and minimizes his contact with Cross and Northline Events.',
    tags: ['statement', 'partial-alibi', 'contradiction'],
    speakerName: 'Elias Ward',
    speakerRole: 'Private auction appraiser',
    recordedAtLabel: '22:28 · 14 OCT',
    locationLabel: 'Auction Lounge',
    paragraphs: [
      { id: 'elias-statement-1', kind: 'quote', text: 'I was at table three from ten past until the alarm. The ticket and camera will confirm it.' },
      { id: 'elias-statement-2', kind: 'paragraph', text: 'I used the telephone niche for one private client call, nothing more.' },
      { id: 'elias-statement-3', kind: 'quote', text: 'Northline is an event contractor. Adrian Cross is merely museum staff I have met at installations.' },
      { id: 'elias-statement-4', kind: 'paragraph', text: 'The Asterion’s provenance makes a secret sale irrational.' },
    ],
    signedBy: 'Elias Ward',
  },
] as const satisfies readonly EvidenceDefinition[];
