import type { FictionalInternetDefinition } from '../../../case-engine';

export const CASE001_INTERNET = {
  sites: [
    {
      id: 'site-hartwell-museum',
      identity: {
        identityId: 'identity-hartwell-museum',
        name: 'Hartwell Museum',
        shortName: 'HM',
        fictionalHost: 'hartwell-museum.invalid',
        tagline: 'Art held in public trust',
        layout: 'institutional',
        logoText: 'HARTWELL MUSEUM',
        typography: 'editorial',
        shape: 'square',
        colors: {
          background: '#ede8dc',
          surface: '#f7f4ec',
          text: '#17232b',
          muted: '#68737a',
          accent: '#8b6239',
          accentSecondary: '#274c5b',
        },
      },
      homePageId: 'hartwell-home',
      pages: [
        {
          id: 'hartwell-home',
          path: '/',
          title: 'Hartwell Museum',
          description: 'The museum’s signed local visitor archive.',
          blocks: [
            { id: 'hartwell-home-heading', type: 'heading', level: 1, text: 'Midnight Gallery' },
            { id: 'hartwell-home-copy', type: 'paragraph', text: 'A patron evening marking the first public display of the Asterion Diamond in thirty-two years.' },
            { id: 'hartwell-home-notice', type: 'notice', label: 'ARCHIVE NOTICE', text: 'This local copy was sealed when the museum entered lockdown at 21:31.', tone: 'warning' },
          ],
          links: [
            { id: 'hartwell-link-event', label: 'View the patron-evening program', targetSiteId: 'site-hartwell-museum', targetPageId: 'hartwell-event', treatment: 'primary' },
            { id: 'hartwell-link-ledger', label: 'Read local coverage', targetSiteId: 'site-lydon-ledger', targetPageId: 'ledger-rook-trust', treatment: 'secondary' },
          ],
          revealsEvidenceIds: [],
          searchTerms: ['museum', 'asterion', 'gala', 'midnight gallery'],
        },
        {
          id: 'hartwell-event',
          path: '/events/midnight-gallery',
          title: 'Midnight Gallery — Patron Evening',
          description: 'Archived gala schedule and visitor program.',
          publishedAtLabel: '14 OCT · ARCHIVED 21:31',
          blocks: [
            { id: 'hartwell-event-heading', type: 'heading', level: 1, text: 'Tonight’s program' },
            { id: 'hartwell-event-list', type: 'list', ordered: true, items: ['20:45 — Curator remarks', '21:14 — Rotunda quartet introduction', '21:30 — Private Asterion viewing', '22:00 — Auction-lounge close'] },
            { id: 'hartwell-event-note', type: 'notice', label: 'FACILITIES', text: 'A brief generator transfer is scheduled during the music program. Display systems remain on isolated power.', tone: 'info' },
          ],
          links: [
            { id: 'hartwell-event-channel', label: 'Channel Eight gala archive', targetSiteId: 'site-channel-eight', targetPageId: 'channel-gala', treatment: 'secondary' },
          ],
          revealsEvidenceIds: ['evidence-web-gala-schedule'],
          searchTerms: ['21:14', '21:30', 'program', 'generator transfer'],
        },
      ],
    },
    {
      id: 'site-lydon-ledger',
      identity: {
        identityId: 'identity-lydon-ledger',
        name: 'The Lydon Ledger',
        shortName: 'LL',
        fictionalHost: 'lydon-ledger.invalid',
        tagline: 'The city, on record',
        layout: 'newsroom',
        logoText: 'THE LYDON LEDGER',
        typography: 'tabloid',
        shape: 'square',
        colors: {
          background: '#f3efe5',
          surface: '#fffdf7',
          text: '#171717',
          muted: '#666158',
          accent: '#9c2f2c',
          accentSecondary: '#2d5264',
        },
      },
      homePageId: 'ledger-home',
      pages: [
        {
          id: 'ledger-home',
          path: '/',
          title: 'The Lydon Ledger',
          description: 'Local reporting preserved in the case archive.',
          publishedAtLabel: 'EVENING EDITION · 14 OCT',
          blocks: [
            { id: 'ledger-home-heading', type: 'heading', level: 1, text: 'Hartwell locks down after gala incident' },
            { id: 'ledger-home-copy', type: 'paragraph', text: 'Police sealed the Hartwell Museum shortly after its headline diamond display was called into question.' },
            { id: 'ledger-home-quote', type: 'quote', text: 'The room was full of cameras. That does not mean every camera was telling the truth.', attribution: 'Witness outside Gallery Four' },
          ],
          links: [
            { id: 'ledger-link-rook', label: 'Background: the Rook trust', targetSiteId: 'site-lydon-ledger', targetPageId: 'ledger-rook-trust', treatment: 'primary' },
            { id: 'ledger-link-neighbour', label: 'Service-lane witness thread', targetSiteId: 'site-neighbourwire', targetPageId: 'neighbour-van-thread', treatment: 'inline' },
          ],
          revealsEvidenceIds: [],
          searchTerms: ['hartwell', 'lockdown', 'diamond', 'camera'],
        },
        {
          id: 'ledger-rook-trust',
          path: '/culture/rook-trust',
          title: 'Rook heir rich in objects, short on cash',
          description: 'A financial background report on the Asterion trust.',
          publishedAtLabel: '10 OCT · 07:20',
          blocks: [
            { id: 'rook-heading', type: 'heading', level: 1, text: 'A fortune no beneficiary can spend' },
            { id: 'rook-copy-1', type: 'paragraph', text: 'Court filings show Julian Rook under immediate financial pressure while the family’s most valuable object remains protected by a restrictive trust.' },
            { id: 'rook-metric', type: 'metric', label: 'DECLARED SHORT-TERM LIABILITIES', value: '4.8m', detail: 'The Asterion cannot legally satisfy them without trustee approval.' },
            { id: 'rook-copy-2', type: 'paragraph', text: 'Private appraiser Elias Ward previously valued two lesser Rook pieces but declined to market the Asterion.' },
          ],
          links: [
            { id: 'rook-link-museum', label: 'Hartwell gala program', targetSiteId: 'site-hartwell-museum', targetPageId: 'hartwell-event', treatment: 'secondary' },
          ],
          revealsEvidenceIds: ['evidence-web-vane-finances'],
          searchTerms: ['Julian Rook', 'debt', 'trust', 'Elias Ward', 'Asterion'],
        },
      ],
    },
    {
      id: 'site-neighbourwire',
      identity: {
        identityId: 'identity-neighbourwire',
        name: 'Lydon Neighbourwire',
        shortName: 'NW',
        fictionalHost: 'lydon-neighbourwire.invalid',
        tagline: 'Street-level notes from people nearby',
        layout: 'community',
        logoText: 'neighbour/wire',
        typography: 'friendly',
        shape: 'pill',
        colors: {
          background: '#182129',
          surface: '#24313b',
          text: '#edf4f4',
          muted: '#9db0b6',
          accent: '#5bd0b0',
          accentSecondary: '#f0a35b',
        },
      },
      homePageId: 'neighbour-home',
      pages: [
        {
          id: 'neighbour-home',
          path: '/',
          title: 'Museum Quarter',
          description: 'Archived local threads from the Hartwell perimeter.',
          blocks: [
            { id: 'neighbour-home-heading', type: 'heading', level: 1, text: 'Museum Quarter threads' },
            { id: 'neighbour-home-post', type: 'post', author: 'NightTram', handle: '@nighttram', timestampLabel: '21:36', body: 'Anyone else see the blank white van waiting behind Hartwell?', reactionLabel: '12 replies' },
          ],
          links: [
            { id: 'neighbour-link-van', label: 'Open service-lane thread', targetSiteId: 'site-neighbourwire', targetPageId: 'neighbour-van-thread', treatment: 'primary' },
          ],
          revealsEvidenceIds: [],
          searchTerms: ['museum quarter', 'van', 'loading lane'],
        },
        {
          id: 'neighbour-van-thread',
          path: '/thread/hartwell-van',
          title: 'Blank van behind Hartwell',
          description: 'Witness posts about a vehicle outside the loading gate.',
          publishedAtLabel: '14 OCT · 21:36–21:58',
          blocks: [
            { id: 'van-thread-post-1', type: 'post', author: 'NightTram', handle: '@nighttram', timestampLabel: '21:36', body: 'White Northline Events van arrived around 21:20. No side logo, driver stayed inside.', reactionLabel: '8 replies' },
            { id: 'van-thread-post-2', type: 'post', author: 'DockWindow', handle: '@dockwindow', timestampLabel: '21:39', body: 'Gate never opened. Security dropped it at 21:31 and the van was still outside.', reactionLabel: 'verified nearby' },
            { id: 'van-thread-notice', type: 'notice', label: 'ARCHIVE NOTE', text: 'The vehicle left only after marked units entered the lane.', tone: 'info' },
          ],
          links: [
            { id: 'van-thread-prism', label: 'Northline-linked prop order', targetSiteId: 'site-prism-props', targetPageId: 'prism-order-4417', treatment: 'inline' },
          ],
          revealsEvidenceIds: ['evidence-web-citythread-van'],
          searchTerms: ['Northline', 'van', 'gate', '21:20', 'loading'],
        },
      ],
    },
    {
      id: 'site-prism-props',
      identity: {
        identityId: 'identity-prism-props',
        name: 'Prism Props & Facsimiles',
        shortName: 'PP',
        fictionalHost: 'prism-props.invalid',
        tagline: 'Impossible objects, safely reproduced',
        layout: 'market',
        logoText: 'PRISM / PROPS',
        typography: 'technical',
        shape: 'soft',
        colors: {
          background: '#10151c',
          surface: '#1b2430',
          text: '#f1f5f7',
          muted: '#96a4b2',
          accent: '#e94f8b',
          accentSecondary: '#42c9db',
        },
      },
      homePageId: 'prism-home',
      openWhen: { kind: 'evidenceDiscovered', evidenceId: 'evidence-photo-replica-macro' },
      pages: [
        {
          id: 'prism-home',
          path: '/',
          title: 'Prism Props',
          description: 'Fabrication catalog and signed order archive.',
          blocks: [
            { id: 'prism-home-heading', type: 'heading', level: 1, text: 'Archival-grade facsimiles' },
            { id: 'prism-home-product', type: 'product', name: 'Optical gemstone reproduction', priceLabel: 'FROM 1,900', description: 'Scan-matched optical crystal for museum, film, and insurance display.', statusLabel: 'MARKED / NON-GEM' },
            { id: 'prism-home-notice', type: 'notice', label: 'WORKSHOP MARK', text: 'Every replica carries the current batch symbol beneath the girdle.', tone: 'info' },
          ],
          links: [
            { id: 'prism-link-catalog', label: 'Read fabrication standard', targetSiteId: 'site-prism-props', targetPageId: 'prism-catalog', treatment: 'secondary' },
            { id: 'prism-link-order', label: 'Open order PP-4417', targetSiteId: 'site-prism-props', targetPageId: 'prism-order-4417', treatment: 'primary' },
          ],
          revealsEvidenceIds: [],
          searchTerms: ['replica', 'facsimile', 'crystal', 'museum', 'star mark'],
        },
        {
          id: 'prism-catalog',
          path: '/catalog/archival-stones',
          title: 'Archival gemstone facsimiles',
          description: 'Workshop identification and ethical marking standard.',
          blocks: [
            { id: 'prism-catalog-heading', type: 'heading', level: 1, text: 'A replica should be excellent—and identifiable' },
            { id: 'prism-catalog-copy', type: 'paragraph', text: 'Prism reproductions carry a micro-mark beneath the girdle. The current batch uses a five-point star 0.4 mm wide.' },
            { id: 'prism-catalog-list', type: 'list', items: ['Scan-matched facet geometry', 'Resin-filled synthetic inclusions', 'Mandatory workshop micro-mark', 'Order-level custody log'] },
          ],
          links: [
            { id: 'prism-catalog-order', label: 'Inspect matching order', targetSiteId: 'site-prism-props', targetPageId: 'prism-order-4417', treatment: 'primary' },
          ],
          revealsEvidenceIds: ['evidence-web-prism-catalog'],
          searchTerms: ['five-point star', 'girdle', '42.2', 'archival stone'],
        },
        {
          id: 'prism-order-4417',
          path: '/orders/pp-4417',
          title: 'Order PP-4417 — controlled archive',
          description: 'Signed local dispatch record for a custom Asterion-profile replica.',
          publishedAtLabel: 'COLLECTED · 13 OCT 16:42',
          blocks: [
            { id: 'prism-order-heading', type: 'heading', level: 1, text: '42.2 ct Asterion-profile facsimile' },
            { id: 'prism-order-profile', type: 'profile', name: 'Northline Events', role: 'Account holder', bio: 'Pickup authorization amended to courier phrase EAST COMMAND.', facts: [{ label: 'ORDER', value: 'PP-4417' }, { label: 'MARK', value: 'FIVE-POINT STAR' }, { label: 'STATUS', value: 'COLLECTED' }] },
            { id: 'prism-order-notice', type: 'notice', label: 'RELEASE EXCEPTION', text: 'Photo identification waived by account holder. Courier used the authorized phrase.', tone: 'urgent' },
          ],
          links: [
            { id: 'prism-order-neighbour', label: 'See Northline van report', targetSiteId: 'site-neighbourwire', targetPageId: 'neighbour-van-thread', treatment: 'inline' },
          ],
          revealsEvidenceIds: ['evidence-receipt-prism-replica', 'evidence-email-replica-order'],
          searchTerms: ['PP-4417', 'Northline', 'East Command', 'Asterion', '42.2'],
        },
      ],
    },
    {
      id: 'site-nia-fieldnotes',
      identity: {
        identityId: 'identity-nia-fieldnotes',
        name: 'Nia Field Notes',
        shortName: 'NF',
        fictionalHost: 'nia-fieldnotes.invalid',
        tagline: 'Documents before conclusions',
        layout: 'personal',
        logoText: 'nia / field notes',
        typography: 'minimal',
        shape: 'soft',
        colors: {
          background: '#f5f0e6',
          surface: '#ebe2d2',
          text: '#2b2a27',
          muted: '#777068',
          accent: '#356b66',
          accentSecondary: '#b45945',
        },
      },
      homePageId: 'nia-home',
      openWhen: { kind: 'evidenceDiscovered', evidenceId: 'evidence-statement-nia' },
      pages: [
        {
          id: 'nia-home',
          path: '/',
          title: 'Nia Field Notes',
          description: 'A reporter’s signed local working archive.',
          blocks: [
            { id: 'nia-home-heading', type: 'heading', level: 1, text: 'Working records' },
            { id: 'nia-home-copy', type: 'paragraph', text: 'Raw files, source-protection notes, and published corrections. Signed at capture so edits remain visible.' },
            { id: 'nia-home-quote', type: 'quote', text: 'A suspicion is not a record. Keep both, label them correctly.', attribution: 'Nia Okafor' },
          ],
          links: [
            { id: 'nia-link-take', label: 'Open Hartwell field take 3', targetSiteId: 'site-nia-fieldnotes', targetPageId: 'nia-hartwell-take', treatment: 'primary' },
          ],
          revealsEvidenceIds: [],
          searchTerms: ['Nia', 'raw file', 'Hartwell', 'field recording'],
        },
        {
          id: 'nia-hartwell-take',
          path: '/archive/hartwell-take-3',
          title: 'Hartwell field take 3 — uncut',
          description: 'Signed continuous recording from the Press Alcove.',
          publishedAtLabel: '14 OCT · 21:22',
          blocks: [
            { id: 'nia-take-heading', type: 'heading', level: 1, text: 'Uncut field recording' },
            { id: 'nia-take-metric', type: 'metric', label: 'CONTINUOUS DURATION', value: '06:16', detail: '21:16:02–21:22:18 / encoder signature intact' },
            { id: 'nia-take-copy', type: 'paragraph', text: 'Rotunda quartet, stage introduction, and generator-transition hum continue without a cut. Device assignment: PRESS-ALCOVE-2.' },
          ],
          links: [
            { id: 'nia-take-channel', label: 'Compare public broadcast', targetSiteId: 'site-channel-eight', targetPageId: 'channel-gala', treatment: 'secondary' },
          ],
          revealsEvidenceIds: ['evidence-web-nia-livestream'],
          searchTerms: ['21:16', '21:22', 'uncut', 'press alcove', 'waveform'],
        },
      ],
    },
    {
      id: 'site-channel-eight',
      identity: {
        identityId: 'identity-channel-eight',
        name: 'Channel Eight Lydon',
        shortName: 'C8',
        fictionalHost: 'channel8-lydon.invalid',
        tagline: 'Lydon live and on record',
        layout: 'broadcast',
        logoText: 'CHANNEL 8 / LYDON',
        typography: 'technical',
        shape: 'pill',
        colors: {
          background: '#080b10',
          surface: '#141a24',
          text: '#f4f6fa',
          muted: '#9da8b9',
          accent: '#f04444',
          accentSecondary: '#4d8dff',
        },
      },
      homePageId: 'channel-home',
      pages: [
        {
          id: 'channel-home',
          path: '/',
          title: 'Channel Eight Lydon',
          description: 'Local newsroom transmission archive.',
          blocks: [
            { id: 'channel-home-heading', type: 'heading', level: 1, text: 'Tonight in Lydon' },
            { id: 'channel-home-notice', type: 'notice', label: 'BREAKING', text: 'Hartwell Museum sealed after a discrepancy was found in the Asterion display.', tone: 'urgent' },
            { id: 'channel-home-copy', type: 'paragraph', text: 'Our gala field encoder preserved independently signed wide shots from the Rotunda.' },
          ],
          links: [
            { id: 'channel-link-gala', label: 'Open gala live archive', targetSiteId: 'site-channel-eight', targetPageId: 'channel-gala', treatment: 'primary' },
            { id: 'channel-link-ledger', label: 'Read Ledger coverage', targetSiteId: 'site-lydon-ledger', targetPageId: 'ledger-home', treatment: 'secondary' },
          ],
          revealsEvidenceIds: [],
          searchTerms: ['breaking', 'Hartwell', 'Asterion', 'gala'],
        },
        {
          id: 'channel-gala',
          path: '/live/hartwell-gala',
          title: 'Inside Hartwell’s Midnight Gallery gala',
          description: 'Signed stills and timecodes from the Rotunda live feed.',
          publishedAtLabel: 'LIVE ARCHIVE · 14 OCT',
          blocks: [
            { id: 'channel-gala-heading', type: 'heading', level: 1, text: 'Rotunda field feed' },
            { id: 'channel-gala-list', type: 'list', items: ['21:14:36 — Vane beside donor dais', '21:17:08 — Vane speaks with quartet sponsor', '21:20:41 — Vane remains in wide frame'] },
            { id: 'channel-gala-metric', type: 'metric', label: 'ENCODER SIGNATURE', value: 'C8-LY-4', detail: 'Independent of Hartwell network' },
          ],
          links: [
            { id: 'channel-gala-nia', label: 'Compare reporter field take', targetSiteId: 'site-nia-fieldnotes', targetPageId: 'nia-hartwell-take', treatment: 'secondary' },
          ],
          revealsEvidenceIds: ['evidence-web-channel8-gallery', 'evidence-photo-gala-wide'],
          searchTerms: ['Celeste Vane', '21:14', '21:17', '21:20', 'encoder'],
        },
      ],
    },
  ],
} as const satisfies FictionalInternetDefinition;
